#pragma once
#pragma execution_character_set("utf-8")
enum UpgradeEvent
{
	UPGRADE_DOWNLOAD_ERROR, //更新失败
	UPGRADE_START_SILENCE_DOWNLOAD, //开始静默下载
	UPGRADE_DOWNLOADING_PROGRESS, //下载进度
	UPGRADE_FINISH_MODULE_DOWNLOAD, //模块下载完成
	UPGRADE_FINISH_DOWNLOAD, //下载完成
	UPGRADE_UNZIPING_PROGRESS, //解压开始
	UPGRADE_FINISH_DOWNLOAD_UNZIP, //下载解压完成
	UPGRADE_GETREMOVE_FILEZIE, //获取远程下载文件的大小
	UPGRADE_RESDOWNLOADADDR_MANUAL_CALLBACK, //资源下载地址获取到后的回调地址
	UPGRADE_RESDOWNLOADADDR_SILENT_CALLBACK,//资源下载地址获取到后的回调地址
	UPGRADE_FINISH_SILENCE_DOWNLOAD, //停止静默下载
	UPGRADE_FINISH_HOT_UPDATE, //lua热更完成
	UPGRADE_UNZIP_MODULE_SUCCESS, //解压模块完成
	UPGRADE_CHECK_MODULE_EXISTS, //监测资源是否存在
	UPGRADE_FINISH_DOWNLOAD_UNZIP_TOLAYER, //下载解压完成UI响应事件


};