--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create back_bg
local back_bg = ccui.ImageView:create()
back_bg:ignoreContentAdaptWithSize(false)
back_bg:loadTexture("res/DuplicateChoiceScene/haiyang2.png",0)
back_bg:setLayoutComponentEnabled(true)
back_bg:setName("back_bg")
back_bg:setTag(167)
back_bg:setCascadeColorEnabled(true)
back_bg:setCascadeOpacityEnabled(true)
back_bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
Scene:addChild(back_bg)

--Create star_bt1
local star_bt1 = ccui.Button:create()
star_bt1:ignoreContentAdaptWithSize(false)
star_bt1:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt1:setTitleFontSize(14)
star_bt1:setTitleColor({r = 65, g = 65, b = 70})
star_bt1:setScale9Enabled(true)
star_bt1:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt1:setLayoutComponentEnabled(true)
star_bt1:setName("star_bt1")
star_bt1:setTag(168)
star_bt1:setCascadeColorEnabled(true)
star_bt1:setCascadeOpacityEnabled(true)
star_bt1:setPosition(399.4735, 133.9821)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt1)
layout:setPositionPercentX(0.5548)
layout:setPositionPercentY(0.1047)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(324.4735)
layout:setRightMargin(245.5265)
layout:setTopMargin(1081.5180)
layout:setBottomMargin(69.4821)
Scene:addChild(star_bt1)

--Create star_bt2
local star_bt2 = ccui.Button:create()
star_bt2:ignoreContentAdaptWithSize(false)
star_bt2:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt2:setTitleFontSize(14)
star_bt2:setTitleColor({r = 65, g = 65, b = 70})
star_bt2:setScale9Enabled(true)
star_bt2:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt2:setLayoutComponentEnabled(true)
star_bt2:setName("star_bt2")
star_bt2:setTag(169)
star_bt2:setCascadeColorEnabled(true)
star_bt2:setCascadeOpacityEnabled(true)
star_bt2:setPosition(326.5730, 355.5989)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt2)
layout:setPositionPercentX(0.4536)
layout:setPositionPercentY(0.2778)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(251.5730)
layout:setRightMargin(318.4270)
layout:setTopMargin(859.9011)
layout:setBottomMargin(291.0989)
Scene:addChild(star_bt2)

--Create star_bt3
local star_bt3 = ccui.Button:create()
star_bt3:ignoreContentAdaptWithSize(false)
star_bt3:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt3:setTitleFontSize(14)
star_bt3:setTitleColor({r = 65, g = 65, b = 70})
star_bt3:setScale9Enabled(true)
star_bt3:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt3:setLayoutComponentEnabled(true)
star_bt3:setName("star_bt3")
star_bt3:setTag(170)
star_bt3:setCascadeColorEnabled(true)
star_bt3:setCascadeOpacityEnabled(true)
star_bt3:setPosition(379.4221, 573.6942)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt3)
layout:setPositionPercentX(0.5270)
layout:setPositionPercentY(0.4482)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(304.4221)
layout:setRightMargin(265.5779)
layout:setTopMargin(641.8058)
layout:setBottomMargin(509.1942)
Scene:addChild(star_bt3)

--Create star_bt4
local star_bt4 = ccui.Button:create()
star_bt4:ignoreContentAdaptWithSize(false)
star_bt4:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt4:setTitleFontSize(14)
star_bt4:setTitleColor({r = 65, g = 65, b = 70})
star_bt4:setScale9Enabled(true)
star_bt4:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt4:setLayoutComponentEnabled(true)
star_bt4:setName("star_bt4")
star_bt4:setTag(171)
star_bt4:setCascadeColorEnabled(true)
star_bt4:setCascadeOpacityEnabled(true)
star_bt4:setPosition(296.7784, 741.9883)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt4)
layout:setPositionPercentX(0.4122)
layout:setPositionPercentY(0.5797)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(221.7784)
layout:setRightMargin(348.2216)
layout:setTopMargin(473.5117)
layout:setBottomMargin(677.4883)
Scene:addChild(star_bt4)

--Create star_bt5
local star_bt5 = ccui.Button:create()
star_bt5:ignoreContentAdaptWithSize(false)
star_bt5:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt5:setTitleFontSize(14)
star_bt5:setTitleColor({r = 65, g = 65, b = 70})
star_bt5:setScale9Enabled(true)
star_bt5:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt5:setLayoutComponentEnabled(true)
star_bt5:setName("star_bt5")
star_bt5:setTag(172)
star_bt5:setCascadeColorEnabled(true)
star_bt5:setCascadeOpacityEnabled(true)
star_bt5:setPosition(248.1044, 934.0969)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt5)
layout:setPositionPercentX(0.3446)
layout:setPositionPercentY(0.7298)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(173.1044)
layout:setRightMargin(396.8956)
layout:setTopMargin(281.4031)
layout:setBottomMargin(869.5969)
Scene:addChild(star_bt5)

--Create star_bt6
local star_bt6 = ccui.Button:create()
star_bt6:ignoreContentAdaptWithSize(false)
star_bt6:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt6:setTitleFontSize(14)
star_bt6:setTitleColor({r = 65, g = 65, b = 70})
star_bt6:setScale9Enabled(true)
star_bt6:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt6:setLayoutComponentEnabled(true)
star_bt6:setName("star_bt6")
star_bt6:setTag(173)
star_bt6:setCascadeColorEnabled(true)
star_bt6:setCascadeOpacityEnabled(true)
star_bt6:setPosition(298.3630, 1084.9220)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt6)
layout:setPositionPercentX(0.4144)
layout:setPositionPercentY(0.8476)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(223.3630)
layout:setRightMargin(346.6370)
layout:setTopMargin(130.5775)
layout:setBottomMargin(1020.4220)
Scene:addChild(star_bt6)

--Create out
local out = ccui.ImageView:create()
out:ignoreContentAdaptWithSize(false)
out:loadTexture("res/DuplicateChoiceScene/chuansong.png",0)
out:setLayoutComponentEnabled(true)
out:setName("out")
out:setTag(154)
out:setCascadeColorEnabled(true)
out:setCascadeOpacityEnabled(true)
out:setPosition(369.2525, 1231.6370)
layout = ccui.LayoutComponent:bindLayoutComponent(out)
layout:setPositionPercentX(0.5129)
layout:setPositionPercentY(0.9622)
layout:setPercentWidth(0.2653)
layout:setPercentHeight(0.1227)
layout:setSize({width = 191.0000, height = 157.0000})
layout:setLeftMargin(273.7525)
layout:setRightMargin(255.2475)
layout:setTopMargin(-30.1366)
layout:setBottomMargin(1153.1370)
Scene:addChild(out)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

