--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create back_bg
local back_bg = ccui.ImageView:create()
back_bg:ignoreContentAdaptWithSize(false)
back_bg:loadTexture("res/DuplicateChoiceScene/niunai1.png",0)
back_bg:setLayoutComponentEnabled(true)
back_bg:setName("back_bg")
back_bg:setTag(179)
back_bg:setCascadeColorEnabled(true)
back_bg:setCascadeOpacityEnabled(true)
back_bg:setPosition(362.7360, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back_bg)
layout:setPositionPercentX(0.5038)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(2.7484)
layout:setRightMargin(-2.7484)
layout:setTopMargin(-0.0002)
layout:setBottomMargin(0.0002)
Scene:addChild(back_bg)

--Create star_bt1
local star_bt1 = ccui.Button:create()
star_bt1:ignoreContentAdaptWithSize(false)
star_bt1:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt1:setTitleFontSize(14)
star_bt1:setTitleColor({r = 65, g = 65, b = 70})
star_bt1:setScale9Enabled(true)
star_bt1:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt1:setLayoutComponentEnabled(true)
star_bt1:setName("star_bt1")
star_bt1:setTag(180)
star_bt1:setCascadeColorEnabled(true)
star_bt1:setCascadeOpacityEnabled(true)
star_bt1:setPosition(485.7848, 197.9758)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt1)
layout:setPositionPercentX(0.6747)
layout:setPositionPercentY(0.1547)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(410.7848)
layout:setRightMargin(159.2152)
layout:setTopMargin(1017.5240)
layout:setBottomMargin(133.4758)
Scene:addChild(star_bt1)

--Create star_bt2
local star_bt2 = ccui.Button:create()
star_bt2:ignoreContentAdaptWithSize(false)
star_bt2:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt2:setTitleFontSize(14)
star_bt2:setTitleColor({r = 65, g = 65, b = 70})
star_bt2:setScale9Enabled(true)
star_bt2:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt2:setLayoutComponentEnabled(true)
star_bt2:setName("star_bt2")
star_bt2:setTag(181)
star_bt2:setCascadeColorEnabled(true)
star_bt2:setCascadeOpacityEnabled(true)
star_bt2:setPosition(385.5707, 329.2339)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt2)
layout:setPositionPercentX(0.5355)
layout:setPositionPercentY(0.2572)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(310.5707)
layout:setRightMargin(259.4293)
layout:setTopMargin(886.2661)
layout:setBottomMargin(264.7339)
Scene:addChild(star_bt2)

--Create star_bt3
local star_bt3 = ccui.Button:create()
star_bt3:ignoreContentAdaptWithSize(false)
star_bt3:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt3:setTitleFontSize(14)
star_bt3:setTitleColor({r = 65, g = 65, b = 70})
star_bt3:setScale9Enabled(true)
star_bt3:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt3:setLayoutComponentEnabled(true)
star_bt3:setName("star_bt3")
star_bt3:setTag(182)
star_bt3:setCascadeColorEnabled(true)
star_bt3:setCascadeOpacityEnabled(true)
star_bt3:setPosition(283.6136, 444.7877)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt3)
layout:setPositionPercentX(0.3939)
layout:setPositionPercentY(0.3475)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(208.6136)
layout:setRightMargin(361.3864)
layout:setTopMargin(770.7123)
layout:setBottomMargin(380.2877)
Scene:addChild(star_bt3)

--Create star_bt4
local star_bt4 = ccui.Button:create()
star_bt4:ignoreContentAdaptWithSize(false)
star_bt4:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt4:setTitleFontSize(14)
star_bt4:setTitleColor({r = 65, g = 65, b = 70})
star_bt4:setScale9Enabled(true)
star_bt4:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt4:setLayoutComponentEnabled(true)
star_bt4:setName("star_bt4")
star_bt4:setTag(183)
star_bt4:setCascadeColorEnabled(true)
star_bt4:setCascadeOpacityEnabled(true)
star_bt4:setPosition(304.3921, 589.8370)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt4)
layout:setPositionPercentX(0.4228)
layout:setPositionPercentY(0.4608)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(229.3921)
layout:setRightMargin(340.6079)
layout:setTopMargin(625.6630)
layout:setBottomMargin(525.3370)
Scene:addChild(star_bt4)

--Create star_bt5
local star_bt5 = ccui.Button:create()
star_bt5:ignoreContentAdaptWithSize(false)
star_bt5:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt5:setTitleFontSize(14)
star_bt5:setTitleColor({r = 65, g = 65, b = 70})
star_bt5:setScale9Enabled(true)
star_bt5:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt5:setLayoutComponentEnabled(true)
star_bt5:setName("star_bt5")
star_bt5:setTag(184)
star_bt5:setCascadeColorEnabled(true)
star_bt5:setCascadeOpacityEnabled(true)
star_bt5:setPosition(386.9152, 721.3835)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt5)
layout:setPositionPercentX(0.5374)
layout:setPositionPercentY(0.5636)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(311.9152)
layout:setRightMargin(258.0848)
layout:setTopMargin(494.1165)
layout:setBottomMargin(656.8835)
Scene:addChild(star_bt5)

--Create star_bt6
local star_bt6 = ccui.Button:create()
star_bt6:ignoreContentAdaptWithSize(false)
star_bt6:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt6:setTitleFontSize(14)
star_bt6:setTitleColor({r = 65, g = 65, b = 70})
star_bt6:setScale9Enabled(true)
star_bt6:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt6:setLayoutComponentEnabled(true)
star_bt6:setName("star_bt6")
star_bt6:setTag(185)
star_bt6:setCascadeColorEnabled(true)
star_bt6:setCascadeOpacityEnabled(true)
star_bt6:setPosition(483.7662, 831.2654)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt6)
layout:setPositionPercentX(0.6719)
layout:setPositionPercentY(0.6494)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(408.7662)
layout:setRightMargin(161.2338)
layout:setTopMargin(384.2346)
layout:setBottomMargin(766.7654)
Scene:addChild(star_bt6)

--Create star_bt7
local star_bt7 = ccui.Button:create()
star_bt7:ignoreContentAdaptWithSize(false)
star_bt7:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt7:setTitleFontSize(14)
star_bt7:setTitleColor({r = 65, g = 65, b = 70})
star_bt7:setScale9Enabled(true)
star_bt7:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt7:setLayoutComponentEnabled(true)
star_bt7:setName("star_bt7")
star_bt7:setTag(69)
star_bt7:setCascadeColorEnabled(true)
star_bt7:setCascadeOpacityEnabled(true)
star_bt7:setPosition(356.4845, 935.6667)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt7)
layout:setPositionPercentX(0.4951)
layout:setPositionPercentY(0.7310)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(281.4845)
layout:setRightMargin(288.5155)
layout:setTopMargin(279.8333)
layout:setBottomMargin(871.1667)
Scene:addChild(star_bt7)

--Create star_bt8
local star_bt8 = ccui.Button:create()
star_bt8:ignoreContentAdaptWithSize(false)
star_bt8:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt8:setTitleFontSize(14)
star_bt8:setTitleColor({r = 65, g = 65, b = 70})
star_bt8:setScale9Enabled(true)
star_bt8:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt8:setLayoutComponentEnabled(true)
star_bt8:setName("star_bt8")
star_bt8:setTag(70)
star_bt8:setCascadeColorEnabled(true)
star_bt8:setCascadeOpacityEnabled(true)
star_bt8:setPosition(255.3516, 1072.7550)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt8)
layout:setPositionPercentX(0.3547)
layout:setPositionPercentY(0.8381)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(180.3516)
layout:setRightMargin(389.6484)
layout:setTopMargin(142.7454)
layout:setBottomMargin(1008.2550)
Scene:addChild(star_bt8)

--Create star_bt9
local star_bt9 = ccui.Button:create()
star_bt9:ignoreContentAdaptWithSize(false)
star_bt9:loadTextureNormal("res/DuplicateChoiceScene/unlocked.png",0)
star_bt9:setTitleFontSize(14)
star_bt9:setTitleColor({r = 65, g = 65, b = 70})
star_bt9:setScale9Enabled(true)
star_bt9:setCapInsets({x = 15, y = 11, width = 120, height = 107})
star_bt9:setLayoutComponentEnabled(true)
star_bt9:setName("star_bt9")
star_bt9:setTag(71)
star_bt9:setCascadeColorEnabled(true)
star_bt9:setCascadeOpacityEnabled(true)
star_bt9:setPosition(347.0673, 1209.8420)
layout = ccui.LayoutComponent:bindLayoutComponent(star_bt9)
layout:setPositionPercentX(0.4820)
layout:setPositionPercentY(0.9452)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.1008)
layout:setSize({width = 150.0000, height = 129.0000})
layout:setLeftMargin(272.0673)
layout:setRightMargin(297.9327)
layout:setTopMargin(5.6580)
layout:setBottomMargin(1145.3420)
Scene:addChild(star_bt9)

--Create enter
local enter = ccui.ImageView:create()
enter:ignoreContentAdaptWithSize(false)
enter:loadTexture("res/DuplicateChoiceScene/chuansong.png",0)
enter:setLayoutComponentEnabled(true)
enter:setName("enter")
enter:setTag(157)
enter:setCascadeColorEnabled(true)
enter:setCascadeOpacityEnabled(true)
enter:setPosition(410.3563, 79.9271)
layout = ccui.LayoutComponent:bindLayoutComponent(enter)
layout:setPositionPercentX(0.5699)
layout:setPositionPercentY(0.0624)
layout:setPercentWidth(0.2653)
layout:setPercentHeight(0.1227)
layout:setSize({width = 191.0000, height = 157.0000})
layout:setLeftMargin(314.8563)
layout:setRightMargin(214.1437)
layout:setTopMargin(1121.5730)
layout:setBottomMargin(1.4271)
Scene:addChild(enter)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

