--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_friend
local Panel_friend = ccui.Layout:create()
Panel_friend:ignoreContentAdaptWithSize(false)
Panel_friend:setClippingEnabled(false)
Panel_friend:setBackGroundColorType(1)
Panel_friend:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_friend:setBackGroundColorOpacity(0)
Panel_friend:setTouchEnabled(true);
Panel_friend:setLayoutComponentEnabled(true)
Panel_friend:setName("Panel_friend")
Panel_friend:setTag(53)
Panel_friend:setCascadeColorEnabled(true)
Panel_friend:setCascadeOpacityEnabled(true)
Panel_friend:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_friend)
layout:setSize({width = 440.0000, height = 560.0000})
layout:setLeftMargin(-220.0000)
layout:setRightMargin(-220.0000)
layout:setTopMargin(-280.0000)
layout:setBottomMargin(-280.0000)
Node:addChild(Panel_friend)

--Create label_connect_facebook
local label_connect_facebook = ccui.TextBMFont:create()
label_connect_facebook:setFntFile("res/GamingLayer/icroncatFont.fnt")
label_connect_facebook:setString([[和facebook朋友一起玩：]])
label_connect_facebook:setLayoutComponentEnabled(true)
label_connect_facebook:setName("label_connect_facebook")
label_connect_facebook:setTag(54)
label_connect_facebook:setCascadeColorEnabled(true)
label_connect_facebook:setCascadeOpacityEnabled(true)
label_connect_facebook:setAnchorPoint(0.0000, 0.5000)
label_connect_facebook:setPosition(40.0000, 533.1005)
label_connect_facebook:setScaleX(0.8000)
label_connect_facebook:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(label_connect_facebook)
layout:setPositionPercentX(0.0909)
layout:setPositionPercentY(0.9520)
layout:setPercentWidth(0.8000)
layout:setPercentHeight(0.0571)
layout:setSize({width = 352.0000, height = 32.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(48.0000)
layout:setTopMargin(10.8995)
layout:setBottomMargin(517.1005)
Panel_friend:addChild(label_connect_facebook)

--Create Button_connect_facebook
local Button_connect_facebook = ccui.Button:create()
Button_connect_facebook:ignoreContentAdaptWithSize(false)
Button_connect_facebook:loadTextureNormal("res/RankLayer/rank_btn_connect.png",0)
Button_connect_facebook:setTitleFontSize(14)
Button_connect_facebook:setTitleColor({r = 65, g = 65, b = 70})
Button_connect_facebook:setScale9Enabled(true)
Button_connect_facebook:setCapInsets({x = 15, y = 11, width = 163, height = 45})
Button_connect_facebook:setLayoutComponentEnabled(true)
Button_connect_facebook:setName("Button_connect_facebook")
Button_connect_facebook:setTag(55)
Button_connect_facebook:setCascadeColorEnabled(true)
Button_connect_facebook:setCascadeOpacityEnabled(true)
Button_connect_facebook:setPosition(318.1783, 463.2256)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_connect_facebook)
layout:setPositionPercentX(0.7231)
layout:setPositionPercentY(0.8272)
layout:setPercentWidth(0.4386)
layout:setPercentHeight(0.1196)
layout:setSize({width = 193.0000, height = 67.0000})
layout:setLeftMargin(221.6783)
layout:setRightMargin(25.3217)
layout:setTopMargin(63.2744)
layout:setBottomMargin(429.7256)
Panel_friend:addChild(Button_connect_facebook)

--Create rank_invite_item_bottom_14
local rank_invite_item_bottom_14 = cc.Sprite:create("res/RankLayer/rank_invite_item_bottom.png")
rank_invite_item_bottom_14:setName("rank_invite_item_bottom_14")
rank_invite_item_bottom_14:setTag(56)
rank_invite_item_bottom_14:setCascadeColorEnabled(true)
rank_invite_item_bottom_14:setCascadeOpacityEnabled(true)
rank_invite_item_bottom_14:setPosition(219.0000, 395.5847)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_invite_item_bottom_14)
layout:setPositionPercentX(0.4977)
layout:setPositionPercentY(0.7064)
layout:setPercentWidth(1.0182)
layout:setPercentHeight(0.0161)
layout:setSize({width = 448.0000, height = 9.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(-3.0000)
layout:setTopMargin(159.9153)
layout:setBottomMargin(391.0847)
rank_invite_item_bottom_14:setBlendFunc({src = 770, dst = 771})
Panel_friend:addChild(rank_invite_item_bottom_14)

--Create label_invite_facebook
local label_invite_facebook = ccui.TextBMFont:create()
label_invite_facebook:setFntFile("res/GamingLayer/icroncatFont.fnt")
label_invite_facebook:setString([[和朋友分享这个游戏：]])
label_invite_facebook:setLayoutComponentEnabled(true)
label_invite_facebook:setName("label_invite_facebook")
label_invite_facebook:setTag(57)
label_invite_facebook:setCascadeColorEnabled(true)
label_invite_facebook:setCascadeOpacityEnabled(true)
label_invite_facebook:setAnchorPoint(0.0000, 0.5000)
label_invite_facebook:setPosition(40.0000, 359.3998)
label_invite_facebook:setScaleX(0.8000)
label_invite_facebook:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(label_invite_facebook)
layout:setPositionPercentX(0.0909)
layout:setPositionPercentY(0.6418)
layout:setPercentWidth(0.7159)
layout:setPercentHeight(0.0571)
layout:setSize({width = 315.0000, height = 32.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(85.0000)
layout:setTopMargin(184.6002)
layout:setBottomMargin(343.3998)
Panel_friend:addChild(label_invite_facebook)

--Create Button_invite_facebook
local Button_invite_facebook = ccui.Button:create()
Button_invite_facebook:ignoreContentAdaptWithSize(false)
Button_invite_facebook:loadTextureNormal("res/RankLayer/rank_btn_invite.png",0)
Button_invite_facebook:setTitleFontSize(14)
Button_invite_facebook:setTitleColor({r = 65, g = 65, b = 70})
Button_invite_facebook:setScale9Enabled(true)
Button_invite_facebook:setCapInsets({x = 15, y = 11, width = 163, height = 45})
Button_invite_facebook:setLayoutComponentEnabled(true)
Button_invite_facebook:setName("Button_invite_facebook")
Button_invite_facebook:setTag(58)
Button_invite_facebook:setCascadeColorEnabled(true)
Button_invite_facebook:setCascadeOpacityEnabled(true)
Button_invite_facebook:setPosition(324.6246, 282.5259)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_invite_facebook)
layout:setPositionPercentX(0.7378)
layout:setPositionPercentY(0.5045)
layout:setPercentWidth(0.4386)
layout:setPercentHeight(0.1196)
layout:setSize({width = 193.0000, height = 67.0000})
layout:setLeftMargin(228.1246)
layout:setRightMargin(18.8754)
layout:setTopMargin(243.9741)
layout:setBottomMargin(249.0259)
Panel_friend:addChild(Button_invite_facebook)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

