--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create pass_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GameTaskLayer/gametask_sprites.plist")
local pass_1 = cc.Sprite:createWithSpriteFrameName("gametask_bg.png")
pass_1:setName("pass_1")
pass_1:setTag(59)
pass_1:setCascadeColorEnabled(true)
pass_1:setCascadeOpacityEnabled(true)
pass_1:setPosition(361.2899, 636.5199)
layout = ccui.LayoutComponent:bindLayoutComponent(pass_1)
layout:setPositionPercentX(0.5018)
layout:setPositionPercentY(0.4973)
layout:setPercentWidth(0.8250)
layout:setPercentHeight(0.4734)
layout:setSize({width = 594.0000, height = 606.0000})
layout:setLeftMargin(64.2899)
layout:setRightMargin(61.7101)
layout:setTopMargin(340.4801)
layout:setBottomMargin(333.5199)
pass_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(pass_1)

--Create BitmapFontLabel_title
local BitmapFontLabel_title = ccui.TextBMFont:create()
BitmapFontLabel_title:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_title:setString([[第1关]])
BitmapFontLabel_title:setLayoutComponentEnabled(true)
BitmapFontLabel_title:setName("BitmapFontLabel_title")
BitmapFontLabel_title:setTag(106)
BitmapFontLabel_title:setCascadeColorEnabled(true)
BitmapFontLabel_title:setCascadeOpacityEnabled(true)
BitmapFontLabel_title:setPosition(361.4429, 887.4619)
BitmapFontLabel_title:setScaleX(1.5000)
BitmapFontLabel_title:setScaleY(1.5000)
BitmapFontLabel_title:setColor({r = 255, g = 165, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_title)
layout:setPositionPercentX(0.5020)
layout:setPositionPercentY(0.6933)
layout:setPercentWidth(0.1194)
layout:setPercentHeight(0.0250)
layout:setSize({width = 86.0000, height = 32.0000})
layout:setLeftMargin(318.4429)
layout:setRightMargin(315.5571)
layout:setTopMargin(376.5381)
layout:setBottomMargin(871.4619)
Layer:addChild(BitmapFontLabel_title)

--Create BitmapFontLabel_1
local BitmapFontLabel_1 = ccui.TextBMFont:create()
BitmapFontLabel_1:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_1:setString([[奖励清单]])
BitmapFontLabel_1:setLayoutComponentEnabled(true)
BitmapFontLabel_1:setName("BitmapFontLabel_1")
BitmapFontLabel_1:setTag(122)
BitmapFontLabel_1:setCascadeColorEnabled(true)
BitmapFontLabel_1:setCascadeOpacityEnabled(true)
BitmapFontLabel_1:setPosition(355.0402, 819.7210)
BitmapFontLabel_1:setColor({r = 239, g = 204, b = 108})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_1)
layout:setPositionPercentX(0.4931)
layout:setPositionPercentY(0.6404)
layout:setPercentWidth(0.1889)
layout:setPercentHeight(0.0250)
layout:setSize({width = 136.0000, height = 32.0000})
layout:setLeftMargin(287.0402)
layout:setRightMargin(296.9598)
layout:setTopMargin(444.2790)
layout:setBottomMargin(803.7210)
Layer:addChild(BitmapFontLabel_1)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setDirection(1)
ListView_1:setGravity(2)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorType(1)
ListView_1:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_1:setBackGroundColorOpacity(0)
ListView_1:setTouchEnabled(false);
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(123)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setAnchorPoint(0.5000, 0.5000)
ListView_1:setPosition(368.3113, 643.1248)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.5115)
layout:setPositionPercentY(0.5024)
layout:setPercentWidth(0.6944)
layout:setPercentHeight(0.2344)
layout:setSize({width = 500.0000, height = 300.0000})
layout:setLeftMargin(118.3113)
layout:setRightMargin(101.6887)
layout:setTopMargin(486.8752)
layout:setBottomMargin(493.1248)
Layer:addChild(ListView_1)

--Create Button_win_lose
local Button_win_lose = ccui.Button:create()
Button_win_lose:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/General/general_sprites.plist")
Button_win_lose:loadTextureNormal("closepressed.png",1)
Button_win_lose:setTitleFontSize(14)
Button_win_lose:setTitleColor({r = 65, g = 65, b = 70})
Button_win_lose:setScale9Enabled(true)
Button_win_lose:setCapInsets({x = 28, y = 30, width = 57, height = 59})
Button_win_lose:setLayoutComponentEnabled(true)
Button_win_lose:setName("Button_win_lose")
Button_win_lose:setTag(64)
Button_win_lose:setCascadeColorEnabled(true)
Button_win_lose:setCascadeOpacityEnabled(true)
Button_win_lose:setPosition(617.0896, 891.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_win_lose)
layout:setPositionPercentX(0.8571)
layout:setPositionPercentY(0.6969)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.0930)
layout:setSize({width = 113.0000, height = 119.0000})
layout:setLeftMargin(560.5896)
layout:setRightMargin(46.4104)
layout:setTopMargin(328.5001)
layout:setBottomMargin(832.4999)
Layer:addChild(Button_win_lose)

--Create Button_win_next
local Button_win_next = ccui.Button:create()
Button_win_next:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GameOverLayer/gameoverlayer_sprites.plist")
Button_win_next:loadTextureNormal("next.png",1)
Button_win_next:setTitleFontSize(14)
Button_win_next:setTitleColor({r = 65, g = 65, b = 70})
Button_win_next:setScale9Enabled(true)
Button_win_next:setCapInsets({x = 21, y = 0, width = 148, height = 67})
Button_win_next:setLayoutComponentEnabled(true)
Button_win_next:setName("Button_win_next")
Button_win_next:setTag(66)
Button_win_next:setCascadeColorEnabled(true)
Button_win_next:setCascadeOpacityEnabled(true)
Button_win_next:setPosition(376.8854, 454.5173)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_win_next)
layout:setPositionPercentX(0.5235)
layout:setPositionPercentY(0.3551)
layout:setPercentWidth(0.2639)
layout:setPercentHeight(0.0523)
layout:setSize({width = 190.0000, height = 67.0000})
layout:setLeftMargin(281.8854)
layout:setRightMargin(248.1146)
layout:setTopMargin(791.9827)
layout:setBottomMargin(421.0173)
Layer:addChild(Button_win_next)

--Create Button_win_share
local Button_win_share = ccui.Button:create()
Button_win_share:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GameOverLayer/gameoverlayer_sprites.plist")
Button_win_share:loadTextureNormal("f_share_bt.png",1)
Button_win_share:setTitleFontSize(14)
Button_win_share:setTitleColor({r = 65, g = 65, b = 70})
Button_win_share:setScale9Enabled(true)
Button_win_share:setCapInsets({x = 15, y = 11, width = 150, height = 40})
Button_win_share:setLayoutComponentEnabled(true)
Button_win_share:setName("Button_win_share")
Button_win_share:setTag(71)
Button_win_share:setCascadeColorEnabled(true)
Button_win_share:setCascadeOpacityEnabled(true)
Button_win_share:setPosition(375.8099, 383.7144)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_win_share)
layout:setPositionPercentX(0.5220)
layout:setPositionPercentY(0.2998)
layout:setPercentWidth(0.2528)
layout:setPercentHeight(0.0500)
layout:setSize({width = 182.0000, height = 64.0000})
layout:setLeftMargin(284.8099)
layout:setRightMargin(253.1901)
layout:setTopMargin(864.2856)
layout:setBottomMargin(351.7144)
Layer:addChild(Button_win_share)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

