--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create gamebg_3_1
local gamebg_3_1 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3.png")
gamebg_3_1:setName("gamebg_3_1")
gamebg_3_1:setTag(68)
gamebg_3_1:setCascadeColorEnabled(true)
gamebg_3_1:setCascadeOpacityEnabled(true)
gamebg_3_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize({width = 720.0000, height = 1280.0000})
gamebg_3_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_1)

--Create gamebg_3_dandelion_3
local gamebg_3_dandelion_3 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_dandelion_3.png")
gamebg_3_dandelion_3:setName("gamebg_3_dandelion_3")
gamebg_3_dandelion_3:setTag(101)
gamebg_3_dandelion_3:setCascadeColorEnabled(true)
gamebg_3_dandelion_3:setCascadeOpacityEnabled(true)
gamebg_3_dandelion_3:setAnchorPoint(0.5618, 0.0000)
gamebg_3_dandelion_3:setPosition(312.9243, 456.1959)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_dandelion_3)
layout:setPositionPercentX(0.4346)
layout:setPositionPercentY(0.3564)
layout:setSize({width = 110.0000, height = 297.0000})
layout:setLeftMargin(251.1316)
layout:setRightMargin(358.8684)
layout:setTopMargin(526.8041)
layout:setBottomMargin(456.1959)
gamebg_3_dandelion_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_dandelion_3)

--Create gamebg_3_dandelion_2
local gamebg_3_dandelion_2 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_dandelion_2.png")
gamebg_3_dandelion_2:setName("gamebg_3_dandelion_2")
gamebg_3_dandelion_2:setTag(102)
gamebg_3_dandelion_2:setCascadeColorEnabled(true)
gamebg_3_dandelion_2:setCascadeOpacityEnabled(true)
gamebg_3_dandelion_2:setAnchorPoint(1.0000, 0.0000)
gamebg_3_dandelion_2:setPosition(153.2933, 412.3248)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_dandelion_2)
layout:setPositionPercentX(0.2129)
layout:setPositionPercentY(0.3221)
layout:setSize({width = 117.0000, height = 304.0000})
layout:setLeftMargin(36.2933)
layout:setRightMargin(566.7067)
layout:setTopMargin(563.6752)
layout:setBottomMargin(412.3248)
gamebg_3_dandelion_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_dandelion_2)

--Create gamebg_3_dandelion_1
local gamebg_3_dandelion_1 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_dandelion_1.png")
gamebg_3_dandelion_1:setName("gamebg_3_dandelion_1")
gamebg_3_dandelion_1:setTag(103)
gamebg_3_dandelion_1:setCascadeColorEnabled(true)
gamebg_3_dandelion_1:setCascadeOpacityEnabled(true)
gamebg_3_dandelion_1:setAnchorPoint(0.1497, 0.0000)
gamebg_3_dandelion_1:setPosition(525.8878, 413.3987)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_dandelion_1)
layout:setPositionPercentX(0.7304)
layout:setPositionPercentY(0.3230)
layout:setSize({width = 113.0000, height = 308.0000})
layout:setLeftMargin(508.9720)
layout:setRightMargin(98.0280)
layout:setTopMargin(558.6013)
layout:setBottomMargin(413.3987)
gamebg_3_dandelion_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_dandelion_1)

--Create gamebg_3_cloud_1
local gamebg_3_cloud_1 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_cloud_1.png")
gamebg_3_cloud_1:setName("gamebg_3_cloud_1")
gamebg_3_cloud_1:setTag(104)
gamebg_3_cloud_1:setCascadeColorEnabled(true)
gamebg_3_cloud_1:setCascadeOpacityEnabled(true)
gamebg_3_cloud_1:setPosition(290.9073, 1121.1370)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_cloud_1)
layout:setPositionPercentX(0.4040)
layout:setPositionPercentY(0.8759)
layout:setSize({width = 614.0000, height = 136.0000})
layout:setLeftMargin(-16.0927)
layout:setRightMargin(122.0927)
layout:setTopMargin(90.8625)
layout:setBottomMargin(1053.1370)
gamebg_3_cloud_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_cloud_1)

--Create gamebg_3_cloud_2
local gamebg_3_cloud_2 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_cloud_2.png")
gamebg_3_cloud_2:setName("gamebg_3_cloud_2")
gamebg_3_cloud_2:setTag(105)
gamebg_3_cloud_2:setCascadeColorEnabled(true)
gamebg_3_cloud_2:setCascadeOpacityEnabled(true)
gamebg_3_cloud_2:setPosition(160.1696, 624.3069)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_cloud_2)
layout:setPositionPercentX(0.2225)
layout:setPositionPercentY(0.4877)
layout:setSize({width = 270.0000, height = 87.0000})
layout:setLeftMargin(25.1696)
layout:setRightMargin(424.8304)
layout:setTopMargin(612.1931)
layout:setBottomMargin(580.8069)
gamebg_3_cloud_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_cloud_2)

--Create gamebg_3_cloud_3
local gamebg_3_cloud_3 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_cloud_3.png")
gamebg_3_cloud_3:setName("gamebg_3_cloud_3")
gamebg_3_cloud_3:setTag(107)
gamebg_3_cloud_3:setCascadeColorEnabled(true)
gamebg_3_cloud_3:setCascadeOpacityEnabled(true)
gamebg_3_cloud_3:setPosition(362.8202, 807.3503)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_cloud_3)
layout:setPositionPercentX(0.5039)
layout:setPositionPercentY(0.6307)
layout:setSize({width = 702.0000, height = 206.0000})
layout:setLeftMargin(11.8202)
layout:setRightMargin(6.1798)
layout:setTopMargin(369.6497)
layout:setBottomMargin(704.3503)
gamebg_3_cloud_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_cloud_3)

--Create gamebg_3_cloud_4
local gamebg_3_cloud_4 = cc.Sprite:create("res/gamescenebg/gamebg_3/gamebg_3_cloud_4.png")
gamebg_3_cloud_4:setName("gamebg_3_cloud_4")
gamebg_3_cloud_4:setTag(106)
gamebg_3_cloud_4:setCascadeColorEnabled(true)
gamebg_3_cloud_4:setCascadeOpacityEnabled(true)
gamebg_3_cloud_4:setPosition(506.6359, 1016.5420)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_3_cloud_4)
layout:setPositionPercentX(0.7037)
layout:setPositionPercentY(0.7942)
layout:setSize({width = 261.0000, height = 86.0000})
layout:setLeftMargin(376.1359)
layout:setRightMargin(82.8641)
layout:setTopMargin(220.4580)
layout:setBottomMargin(973.5419)
gamebg_3_cloud_4:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_3_cloud_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

