--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create gamebg_5_1
local gamebg_5_1 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5.png")
gamebg_5_1:setName("gamebg_5_1")
gamebg_5_1:setTag(68)
gamebg_5_1:setCascadeColorEnabled(true)
gamebg_5_1:setCascadeOpacityEnabled(true)
gamebg_5_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize({width = 720.0000, height = 1280.0000})
gamebg_5_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_1)

--Create gamebg_5_stars_4
local gamebg_5_stars_4 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5_stars.png")
gamebg_5_stars_4:setName("gamebg_5_stars_4")
gamebg_5_stars_4:setTag(166)
gamebg_5_stars_4:setCascadeColorEnabled(true)
gamebg_5_stars_4:setCascadeOpacityEnabled(true)
gamebg_5_stars_4:setPosition(156.6359, 788.3953)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_stars_4)
layout:setPositionPercentX(0.2175)
layout:setPositionPercentY(0.6159)
layout:setSize({width = 104.0000, height = 123.0000})
layout:setLeftMargin(104.6359)
layout:setRightMargin(511.3641)
layout:setTopMargin(430.1047)
layout:setBottomMargin(726.8953)
gamebg_5_stars_4:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_stars_4)

--Create gamebg_5_stars_5
local gamebg_5_stars_5 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5_stars.png")
gamebg_5_stars_5:setName("gamebg_5_stars_5")
gamebg_5_stars_5:setTag(167)
gamebg_5_stars_5:setCascadeColorEnabled(true)
gamebg_5_stars_5:setCascadeOpacityEnabled(true)
gamebg_5_stars_5:setPosition(589.9904, 1086.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_stars_5)
layout:setPositionPercentX(0.8194)
layout:setPositionPercentY(0.8484)
layout:setSize({width = 104.0000, height = 123.0000})
layout:setLeftMargin(537.9904)
layout:setRightMargin(78.0096)
layout:setTopMargin(132.5001)
layout:setBottomMargin(1024.5000)
gamebg_5_stars_5:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_stars_5)

--Create gamebg_5_stars_6
local gamebg_5_stars_6 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5_stars.png")
gamebg_5_stars_6:setName("gamebg_5_stars_6")
gamebg_5_stars_6:setTag(168)
gamebg_5_stars_6:setCascadeColorEnabled(true)
gamebg_5_stars_6:setCascadeOpacityEnabled(true)
gamebg_5_stars_6:setPosition(532.5587, 845.8276)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_stars_6)
layout:setPositionPercentX(0.7397)
layout:setPositionPercentY(0.6608)
layout:setSize({width = 104.0000, height = 123.0000})
layout:setLeftMargin(480.5587)
layout:setRightMargin(135.4413)
layout:setTopMargin(372.6724)
layout:setBottomMargin(784.3276)
gamebg_5_stars_6:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_stars_6)

--Create gamebg_5_cloud_1
local gamebg_5_cloud_1 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5_cloud_1.png")
gamebg_5_cloud_1:setName("gamebg_5_cloud_1")
gamebg_5_cloud_1:setTag(163)
gamebg_5_cloud_1:setCascadeColorEnabled(true)
gamebg_5_cloud_1:setCascadeOpacityEnabled(true)
gamebg_5_cloud_1:setPosition(506.4550, 710.0783)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_cloud_1)
layout:setPositionPercentX(0.7034)
layout:setPositionPercentY(0.5547)
layout:setSize({width = 270.0000, height = 87.0000})
layout:setLeftMargin(371.4550)
layout:setRightMargin(78.5450)
layout:setTopMargin(526.4217)
layout:setBottomMargin(666.5783)
gamebg_5_cloud_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_cloud_1)

--Create gamebg_5_cloud_3
local gamebg_5_cloud_3 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5_cloud_3.png")
gamebg_5_cloud_3:setName("gamebg_5_cloud_3")
gamebg_5_cloud_3:setTag(164)
gamebg_5_cloud_3:setCascadeColorEnabled(true)
gamebg_5_cloud_3:setCascadeOpacityEnabled(true)
gamebg_5_cloud_3:setPosition(135.7516, 882.3764)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_cloud_3)
layout:setPositionPercentX(0.1885)
layout:setPositionPercentY(0.6894)
layout:setSize({width = 262.0000, height = 86.0000})
layout:setLeftMargin(4.7516)
layout:setRightMargin(453.2484)
layout:setTopMargin(354.6236)
layout:setBottomMargin(839.3764)
gamebg_5_cloud_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_cloud_3)

--Create gamebg_5_cloud_2
local gamebg_5_cloud_2 = cc.Sprite:create("res/gamescenebg/gamebg_5/gamebg_5_cloud_2.png")
gamebg_5_cloud_2:setName("gamebg_5_cloud_2")
gamebg_5_cloud_2:setTag(165)
gamebg_5_cloud_2:setCascadeColorEnabled(true)
gamebg_5_cloud_2:setCascadeOpacityEnabled(true)
gamebg_5_cloud_2:setPosition(506.4525, 997.2408)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_5_cloud_2)
layout:setPositionPercentX(0.7034)
layout:setPositionPercentY(0.7791)
layout:setSize({width = 391.0000, height = 93.0000})
layout:setLeftMargin(310.9525)
layout:setRightMargin(18.0475)
layout:setTopMargin(236.2593)
layout:setBottomMargin(950.7408)
gamebg_5_cloud_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_5_cloud_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

