--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create gamebg_2_1
local gamebg_2_1 = cc.Sprite:create("res/gamescenebg/gamebg_2/gamebg_2.png")
gamebg_2_1:setName("gamebg_2_1")
gamebg_2_1:setTag(68)
gamebg_2_1:setCascadeColorEnabled(true)
gamebg_2_1:setCascadeOpacityEnabled(true)
gamebg_2_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_2_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize({width = 720.0000, height = 1280.0000})
gamebg_2_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_2_1)

--Create gamebg_2_boat
local gamebg_2_boat = cc.Sprite:create("res/gamescenebg/gamebg_2/gamebg_2_boat.png")
gamebg_2_boat:setName("gamebg_2_boat")
gamebg_2_boat:setTag(89)
gamebg_2_boat:setCascadeColorEnabled(true)
gamebg_2_boat:setCascadeOpacityEnabled(true)
gamebg_2_boat:setPosition(311.4264, 524.7122)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_2_boat)
layout:setPositionPercentX(0.4325)
layout:setPositionPercentY(0.4099)
layout:setSize({width = 142.0000, height = 123.0000})
layout:setLeftMargin(240.4264)
layout:setRightMargin(337.5736)
layout:setTopMargin(693.7878)
layout:setBottomMargin(463.2122)
gamebg_2_boat:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_2_boat)

--Create gamebg_2_cloud_1
local gamebg_2_cloud_1 = cc.Sprite:create("res/gamescenebg/gamebg_2/gamebg_2_cloud_1.png")
gamebg_2_cloud_1:setName("gamebg_2_cloud_1")
gamebg_2_cloud_1:setTag(90)
gamebg_2_cloud_1:setCascadeColorEnabled(true)
gamebg_2_cloud_1:setCascadeOpacityEnabled(true)
gamebg_2_cloud_1:setPosition(330.1302, 879.2593)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_2_cloud_1)
layout:setPositionPercentX(0.4585)
layout:setPositionPercentY(0.6869)
layout:setSize({width = 631.0000, height = 116.0000})
layout:setLeftMargin(14.6302)
layout:setRightMargin(74.3698)
layout:setTopMargin(342.7407)
layout:setBottomMargin(821.2593)
gamebg_2_cloud_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_2_cloud_1)

--Create gamebg_2_cloud_2
local gamebg_2_cloud_2 = cc.Sprite:create("res/gamescenebg/gamebg_2/gamebg_2_cloud_2.png")
gamebg_2_cloud_2:setName("gamebg_2_cloud_2")
gamebg_2_cloud_2:setTag(91)
gamebg_2_cloud_2:setCascadeColorEnabled(true)
gamebg_2_cloud_2:setCascadeOpacityEnabled(true)
gamebg_2_cloud_2:setPosition(356.2780, 1049.2280)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_2_cloud_2)
layout:setPositionPercentX(0.4948)
layout:setPositionPercentY(0.8197)
layout:setSize({width = 725.0000, height = 144.0000})
layout:setLeftMargin(-6.2220)
layout:setRightMargin(1.2220)
layout:setTopMargin(158.7725)
layout:setBottomMargin(977.2275)
gamebg_2_cloud_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_2_cloud_2)

--Create gamebg_2_cloud_3
local gamebg_2_cloud_3 = cc.Sprite:create("res/gamescenebg/gamebg_2/gamebg_2_cloud_3.png")
gamebg_2_cloud_3:setName("gamebg_2_cloud_3")
gamebg_2_cloud_3:setTag(92)
gamebg_2_cloud_3:setCascadeColorEnabled(true)
gamebg_2_cloud_3:setCascadeOpacityEnabled(true)
gamebg_2_cloud_3:setPosition(558.9337, 1186.5100)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_2_cloud_3)
layout:setPositionPercentX(0.7763)
layout:setPositionPercentY(0.9270)
layout:setSize({width = 261.0000, height = 86.0000})
layout:setLeftMargin(428.4337)
layout:setRightMargin(30.5663)
layout:setTopMargin(50.4895)
layout:setBottomMargin(1143.5100)
gamebg_2_cloud_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_2_cloud_3)

--Create gamebg_2_whale
local gamebg_2_whale = cc.Sprite:create("res/gamescenebg/gamebg_2/gamebg_2_whale.png")
gamebg_2_whale:setName("gamebg_2_whale")
gamebg_2_whale:setTag(93)
gamebg_2_whale:setCascadeColorEnabled(true)
gamebg_2_whale:setCascadeOpacityEnabled(true)
gamebg_2_whale:setPosition(539.3239, 303.9825)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_2_whale)
layout:setPositionPercentX(0.7491)
layout:setPositionPercentY(0.2375)
layout:setSize({width = 274.0000, height = 202.0000})
layout:setLeftMargin(402.3239)
layout:setRightMargin(43.6761)
layout:setTopMargin(875.0175)
layout:setBottomMargin(202.9825)
gamebg_2_whale:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_2_whale)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

