--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(123)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(187)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Panel_1)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GamePauseLayer/gamepause_sprites.plist")
Image_bg:loadTexture("pause_bg.png",1)
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(188)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(360.0000, 646.3118)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5049)
layout:setPercentWidth(0.8250)
layout:setPercentHeight(0.4109)
layout:setSize({width = 594.0000, height = 526.0000})
layout:setLeftMargin(63.0000)
layout:setRightMargin(63.0000)
layout:setTopMargin(370.6882)
layout:setBottomMargin(383.3118)
Layer:addChild(Image_bg)

--Create BitmapFontLabel_tollgate
local BitmapFontLabel_tollgate = ccui.TextBMFont:create()
BitmapFontLabel_tollgate:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_tollgate:setString([[第1关]])
BitmapFontLabel_tollgate:setLayoutComponentEnabled(true)
BitmapFontLabel_tollgate:setName("BitmapFontLabel_tollgate")
BitmapFontLabel_tollgate:setTag(50)
BitmapFontLabel_tollgate:setCascadeColorEnabled(true)
BitmapFontLabel_tollgate:setCascadeOpacityEnabled(true)
BitmapFontLabel_tollgate:setPosition(296.0337, 463.6627)
BitmapFontLabel_tollgate:setScaleX(1.6000)
BitmapFontLabel_tollgate:setScaleY(1.6000)
BitmapFontLabel_tollgate:setColor({r = 123, g = 185, b = 191})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_tollgate)
layout:setPositionPercentX(0.4984)
layout:setPositionPercentY(0.8815)
layout:setPercentWidth(0.1448)
layout:setPercentHeight(0.0608)
layout:setSize({width = 86.0000, height = 32.0000})
layout:setLeftMargin(253.0337)
layout:setRightMargin(254.9663)
layout:setTopMargin(46.3373)
layout:setBottomMargin(447.6627)
Image_bg:addChild(BitmapFontLabel_tollgate)

--Create ListView_pause_task
local ListView_pause_task = ccui.ListView:create()
ListView_pause_task:setDirection(1)
ListView_pause_task:setGravity(0)
ListView_pause_task:ignoreContentAdaptWithSize(false)
ListView_pause_task:setClippingEnabled(false)
ListView_pause_task:setBackGroundColorType(1)
ListView_pause_task:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_pause_task:setBackGroundColorOpacity(0)
ListView_pause_task:setLayoutComponentEnabled(true)
ListView_pause_task:setName("ListView_pause_task")
ListView_pause_task:setTag(70)
ListView_pause_task:setCascadeColorEnabled(true)
ListView_pause_task:setCascadeOpacityEnabled(true)
ListView_pause_task:setPosition(55.5282, 191.6785)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_pause_task)
layout:setPositionPercentX(0.0935)
layout:setPositionPercentY(0.3644)
layout:setPercentWidth(0.8418)
layout:setPercentHeight(0.3802)
layout:setSize({width = 500.0000, height = 200.0000})
layout:setLeftMargin(55.5282)
layout:setRightMargin(38.4718)
layout:setTopMargin(134.3215)
layout:setBottomMargin(191.6785)
Image_bg:addChild(ListView_pause_task)

--Create Button_pause_continue
local Button_pause_continue = ccui.Button:create()
Button_pause_continue:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GamePauseLayer/gamepause_sprites.plist")
Button_pause_continue:loadTextureNormal("pause_continue.png",1)
Button_pause_continue:setTitleFontSize(14)
Button_pause_continue:setTitleColor({r = 65, g = 65, b = 70})
Button_pause_continue:setScale9Enabled(true)
Button_pause_continue:setCapInsets({x = 0, y = 0, width = 112, height = 88})
Button_pause_continue:setLayoutComponentEnabled(true)
Button_pause_continue:setName("Button_pause_continue")
Button_pause_continue:setTag(48)
Button_pause_continue:setCascadeColorEnabled(true)
Button_pause_continue:setCascadeOpacityEnabled(true)
Button_pause_continue:setPosition(399.2252, 110.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_pause_continue)
layout:setPositionPercentX(0.6721)
layout:setPositionPercentY(0.2091)
layout:setPercentWidth(0.1886)
layout:setPercentHeight(0.1673)
layout:setSize({width = 112.0000, height = 88.0000})
layout:setLeftMargin(343.2252)
layout:setRightMargin(138.7748)
layout:setTopMargin(372.0000)
layout:setBottomMargin(66.0000)
Image_bg:addChild(Button_pause_continue)

--Create Button_pause_home
local Button_pause_home = ccui.Button:create()
Button_pause_home:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GamePauseLayer/gamepause_sprites.plist")
Button_pause_home:loadTextureNormal("pause_home.png",1)
Button_pause_home:setTitleFontSize(14)
Button_pause_home:setTitleColor({r = 65, g = 65, b = 70})
Button_pause_home:setScale9Enabled(true)
Button_pause_home:setCapInsets({x = 0, y = 0, width = 112, height = 88})
Button_pause_home:setLayoutComponentEnabled(true)
Button_pause_home:setName("Button_pause_home")
Button_pause_home:setTag(49)
Button_pause_home:setCascadeColorEnabled(true)
Button_pause_home:setCascadeOpacityEnabled(true)
Button_pause_home:setPosition(220.0223, 110.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_pause_home)
layout:setPositionPercentX(0.3704)
layout:setPositionPercentY(0.2091)
layout:setPercentWidth(0.1886)
layout:setPercentHeight(0.1673)
layout:setSize({width = 112.0000, height = 88.0000})
layout:setLeftMargin(164.0223)
layout:setRightMargin(317.9777)
layout:setTopMargin(372.0000)
layout:setBottomMargin(66.0000)
Image_bg:addChild(Button_pause_home)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

