--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create gamebg_4_1
local gamebg_4_1 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4.png")
gamebg_4_1:setName("gamebg_4_1")
gamebg_4_1:setTag(68)
gamebg_4_1:setCascadeColorEnabled(true)
gamebg_4_1:setCascadeOpacityEnabled(true)
gamebg_4_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize({width = 720.0000, height = 1280.0000})
gamebg_4_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(gamebg_4_1)

--Create gamebg_4_ghost_3
local gamebg_4_ghost_3 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_ghost_3.png")
gamebg_4_ghost_3:setName("gamebg_4_ghost_3")
gamebg_4_ghost_3:setTag(131)
gamebg_4_ghost_3:setCascadeColorEnabled(true)
gamebg_4_ghost_3:setCascadeOpacityEnabled(true)
gamebg_4_ghost_3:setPosition(88.2533, 794.2758)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_ghost_3)
layout:setPositionPercentX(0.1226)
layout:setPositionPercentY(0.6205)
layout:setSize({width = 130.0000, height = 88.0000})
layout:setLeftMargin(23.2533)
layout:setRightMargin(566.7467)
layout:setTopMargin(441.7242)
layout:setBottomMargin(750.2758)
gamebg_4_ghost_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_ghost_3)

--Create gamebg_4_ghost_2
local gamebg_4_ghost_2 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_ghost_2.png")
gamebg_4_ghost_2:setName("gamebg_4_ghost_2")
gamebg_4_ghost_2:setTag(132)
gamebg_4_ghost_2:setCascadeColorEnabled(true)
gamebg_4_ghost_2:setCascadeOpacityEnabled(true)
gamebg_4_ghost_2:setPosition(611.2311, 624.3085)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_ghost_2)
layout:setPositionPercentX(0.8489)
layout:setPositionPercentY(0.4877)
layout:setSize({width = 104.0000, height = 80.0000})
layout:setLeftMargin(559.2311)
layout:setRightMargin(56.7689)
layout:setTopMargin(615.6915)
layout:setBottomMargin(584.3085)
gamebg_4_ghost_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_ghost_2)

--Create gamebg_4_ghost_1
local gamebg_4_ghost_1 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_ghost_1.png")
gamebg_4_ghost_1:setName("gamebg_4_ghost_1")
gamebg_4_ghost_1:setTag(133)
gamebg_4_ghost_1:setCascadeColorEnabled(true)
gamebg_4_ghost_1:setCascadeOpacityEnabled(true)
gamebg_4_ghost_1:setPosition(421.6515, 336.6682)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_ghost_1)
layout:setPositionPercentX(0.5856)
layout:setPositionPercentY(0.2630)
layout:setSize({width = 72.0000, height = 83.0000})
layout:setLeftMargin(385.6515)
layout:setRightMargin(262.3485)
layout:setTopMargin(901.8318)
layout:setBottomMargin(295.1682)
gamebg_4_ghost_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_ghost_1)

--Create gamebg_4_birds_1
local gamebg_4_birds_1 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_birds_1.png")
gamebg_4_birds_1:setName("gamebg_4_birds_1")
gamebg_4_birds_1:setTag(134)
gamebg_4_birds_1:setCascadeColorEnabled(true)
gamebg_4_birds_1:setCascadeOpacityEnabled(true)
gamebg_4_birds_1:setPosition(277.8329, 905.4084)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_birds_1)
layout:setPositionPercentX(0.3859)
layout:setPositionPercentY(0.7074)
layout:setSize({width = 183.0000, height = 131.0000})
layout:setLeftMargin(186.3329)
layout:setRightMargin(350.6671)
layout:setTopMargin(309.0916)
layout:setBottomMargin(839.9084)
gamebg_4_birds_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_birds_1)

--Create gamebg_4_birds_2
local gamebg_4_birds_2 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_birds_2.png")
gamebg_4_birds_2:setName("gamebg_4_birds_2")
gamebg_4_birds_2:setTag(135)
gamebg_4_birds_2:setCascadeColorEnabled(true)
gamebg_4_birds_2:setCascadeOpacityEnabled(true)
gamebg_4_birds_2:setPosition(617.7689, 846.5016)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_birds_2)
layout:setPositionPercentX(0.8580)
layout:setPositionPercentY(0.6613)
layout:setSize({width = 67.0000, height = 76.0000})
layout:setLeftMargin(584.2689)
layout:setRightMargin(68.7311)
layout:setTopMargin(395.4984)
layout:setBottomMargin(808.5016)
gamebg_4_birds_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_birds_2)

--Create gamebg_4_cloud_1
local gamebg_4_cloud_1 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_cloud_1.png")
gamebg_4_cloud_1:setName("gamebg_4_cloud_1")
gamebg_4_cloud_1:setTag(136)
gamebg_4_cloud_1:setCascadeColorEnabled(true)
gamebg_4_cloud_1:setCascadeOpacityEnabled(true)
gamebg_4_cloud_1:setPosition(165.8176, 945.3407)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_cloud_1)
layout:setPositionPercentX(0.2303)
layout:setPositionPercentY(0.7385)
layout:setSize({width = 270.0000, height = 87.0000})
layout:setLeftMargin(30.8176)
layout:setRightMargin(419.1824)
layout:setTopMargin(291.1593)
layout:setBottomMargin(901.8407)
gamebg_4_cloud_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_cloud_1)

--Create gamebg_4_cloud_2
local gamebg_4_cloud_2 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_cloud_2.png")
gamebg_4_cloud_2:setName("gamebg_4_cloud_2")
gamebg_4_cloud_2:setTag(137)
gamebg_4_cloud_2:setCascadeColorEnabled(true)
gamebg_4_cloud_2:setCascadeOpacityEnabled(true)
gamebg_4_cloud_2:setPosition(552.1852, 914.0139)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_cloud_2)
layout:setPositionPercentX(0.7669)
layout:setPositionPercentY(0.7141)
layout:setSize({width = 271.0000, height = 87.0000})
layout:setLeftMargin(416.6852)
layout:setRightMargin(32.3148)
layout:setTopMargin(322.4861)
layout:setBottomMargin(870.5139)
gamebg_4_cloud_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_cloud_2)

--Create gamebg_4_cloud_3
local gamebg_4_cloud_3 = cc.Sprite:create("res/gamescenebg/gamebg_4/gamebg_4_cloud_3.png")
gamebg_4_cloud_3:setName("gamebg_4_cloud_3")
gamebg_4_cloud_3:setTag(138)
gamebg_4_cloud_3:setCascadeColorEnabled(true)
gamebg_4_cloud_3:setCascadeOpacityEnabled(true)
gamebg_4_cloud_3:setPosition(238.9147, 668.6201)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_4_cloud_3)
layout:setPositionPercentX(0.3318)
layout:setPositionPercentY(0.5224)
layout:setSize({width = 262.0000, height = 86.0000})
layout:setLeftMargin(107.9147)
layout:setRightMargin(350.0853)
layout:setTopMargin(568.3799)
layout:setBottomMargin(625.6201)
gamebg_4_cloud_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_4_cloud_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

