--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create gamebg_1_1
local gamebg_1_1 = cc.Sprite:create("res/gamescenebg/gamebg_1/gamebg_1.png")
gamebg_1_1:setName("gamebg_1_1")
gamebg_1_1:setTag(68)
gamebg_1_1:setCascadeColorEnabled(true)
gamebg_1_1:setCascadeOpacityEnabled(true)
gamebg_1_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_1_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize({width = 720.0000, height = 1280.0000})
gamebg_1_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_1_1)

--Create gamebg_1_cloud_1_2
local gamebg_1_cloud_1_2 = cc.Sprite:create("res/gamescenebg/gamebg_1/gamebg_1_cloud_1.png")
gamebg_1_cloud_1_2:setName("gamebg_1_cloud_1_2")
gamebg_1_cloud_1_2:setTag(69)
gamebg_1_cloud_1_2:setCascadeColorEnabled(true)
gamebg_1_cloud_1_2:setCascadeOpacityEnabled(true)
gamebg_1_cloud_1_2:setPosition(169.6891, 1080.7800)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_1_cloud_1_2)
layout:setPositionPercentX(0.2357)
layout:setPositionPercentY(0.8444)
layout:setSize({width = 246.0000, height = 78.0000})
layout:setLeftMargin(46.6891)
layout:setRightMargin(427.3109)
layout:setTopMargin(160.2205)
layout:setBottomMargin(1041.7800)
gamebg_1_cloud_1_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_1_cloud_1_2)

--Create gamebg_1_cloud_2_3
local gamebg_1_cloud_2_3 = cc.Sprite:create("res/gamescenebg/gamebg_1/gamebg_1_cloud_2.png")
gamebg_1_cloud_2_3:setName("gamebg_1_cloud_2_3")
gamebg_1_cloud_2_3:setTag(70)
gamebg_1_cloud_2_3:setCascadeColorEnabled(true)
gamebg_1_cloud_2_3:setCascadeOpacityEnabled(true)
gamebg_1_cloud_2_3:setPosition(435.9679, 898.0401)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_1_cloud_2_3)
layout:setPositionPercentX(0.6055)
layout:setPositionPercentY(0.7016)
layout:setSize({width = 240.0000, height = 79.0000})
layout:setLeftMargin(315.9679)
layout:setRightMargin(164.0321)
layout:setTopMargin(342.4599)
layout:setBottomMargin(858.5401)
gamebg_1_cloud_2_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_1_cloud_2_3)

--Create gamebg_1_windmill_1_4
local gamebg_1_windmill_1_4 = cc.Sprite:create("res/gamescenebg/gamebg_1/gamebg_1_windmill_1.png")
gamebg_1_windmill_1_4:setName("gamebg_1_windmill_1_4")
gamebg_1_windmill_1_4:setTag(71)
gamebg_1_windmill_1_4:setCascadeColorEnabled(true)
gamebg_1_windmill_1_4:setCascadeOpacityEnabled(true)
gamebg_1_windmill_1_4:setPosition(341.9868, 699.6346)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_1_windmill_1_4)
layout:setPositionPercentX(0.4750)
layout:setPositionPercentY(0.5466)
layout:setSize({width = 251.0000, height = 253.0000})
layout:setLeftMargin(216.4868)
layout:setRightMargin(252.5132)
layout:setTopMargin(453.8654)
layout:setBottomMargin(573.1346)
gamebg_1_windmill_1_4:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_1_windmill_1_4)

--Create gamebg_1_windmill_2_5
local gamebg_1_windmill_2_5 = cc.Sprite:create("res/gamescenebg/gamebg_1/gamebg_1_windmill_2.png")
gamebg_1_windmill_2_5:setName("gamebg_1_windmill_2_5")
gamebg_1_windmill_2_5:setTag(72)
gamebg_1_windmill_2_5:setCascadeColorEnabled(true)
gamebg_1_windmill_2_5:setCascadeOpacityEnabled(true)
gamebg_1_windmill_2_5:setPosition(519.5059, 589.9905)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_1_windmill_2_5)
layout:setPositionPercentX(0.7215)
layout:setPositionPercentY(0.4609)
layout:setSize({width = 124.0000, height = 125.0000})
layout:setLeftMargin(457.5059)
layout:setRightMargin(138.4941)
layout:setTopMargin(627.5095)
layout:setBottomMargin(527.4905)
gamebg_1_windmill_2_5:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_1_windmill_2_5)

--Create gamebg_1_birds_6
local gamebg_1_birds_6 = cc.Sprite:create("res/gamescenebg/gamebg_1/gamebg_1_birds.png")
gamebg_1_birds_6:setName("gamebg_1_birds_6")
gamebg_1_birds_6:setTag(73)
gamebg_1_birds_6:setCascadeColorEnabled(true)
gamebg_1_birds_6:setCascadeOpacityEnabled(true)
gamebg_1_birds_6:setPosition(587.3822, 741.4037)
layout = ccui.LayoutComponent:bindLayoutComponent(gamebg_1_birds_6)
layout:setPositionPercentX(0.8158)
layout:setPositionPercentY(0.5792)
layout:setSize({width = 156.0000, height = 143.0000})
layout:setLeftMargin(509.3822)
layout:setRightMargin(54.6178)
layout:setTopMargin(467.0963)
layout:setBottomMargin(669.9037)
gamebg_1_birds_6:setBlendFunc({src = 770, dst = 771})
Layer:addChild(gamebg_1_birds_6)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

