--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GameTaskLayer/gametask_sprites.plist")
Panel_1:setBackGroundImage("gametask_circleblank.png",1)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(82)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 105.0000, height = 105.0000})
layout:setLeftMargin(-52.5000)
layout:setRightMargin(-52.5000)
layout:setTopMargin(-52.5000)
layout:setBottomMargin(-52.5000)
Node:addChild(Panel_1)

--Create sprite_normalitem_icon
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GameOverLayer/gameoverlayer_sprites.plist")
local sprite_normalitem_icon = cc.Sprite:createWithSpriteFrameName("over_fish_0.png")
sprite_normalitem_icon:setName("sprite_normalitem_icon")
sprite_normalitem_icon:setTag(84)
sprite_normalitem_icon:setCascadeColorEnabled(true)
sprite_normalitem_icon:setCascadeOpacityEnabled(true)
sprite_normalitem_icon:setPosition(55.2722, 52.6901)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite_normalitem_icon)
layout:setPositionPercentX(0.5264)
layout:setPositionPercentY(0.5018)
layout:setPercentWidth(0.4381)
layout:setPercentHeight(0.5333)
layout:setSize({width = 46.0000, height = 56.0000})
layout:setLeftMargin(32.2722)
layout:setRightMargin(26.7278)
layout:setTopMargin(24.3099)
layout:setBottomMargin(24.6901)
sprite_normalitem_icon:setBlendFunc({src = 770, dst = 771})
Panel_1:addChild(sprite_normalitem_icon)

--Create BitmapFontLabel_normalitem_num
local BitmapFontLabel_normalitem_num = ccui.TextBMFont:create()
BitmapFontLabel_normalitem_num:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_normalitem_num:setString([[+0]])
BitmapFontLabel_normalitem_num:setLayoutComponentEnabled(true)
BitmapFontLabel_normalitem_num:setName("BitmapFontLabel_normalitem_num")
BitmapFontLabel_normalitem_num:setTag(85)
BitmapFontLabel_normalitem_num:setCascadeColorEnabled(true)
BitmapFontLabel_normalitem_num:setCascadeOpacityEnabled(true)
BitmapFontLabel_normalitem_num:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_normalitem_num:setPosition(70.4718, 18.0935)
BitmapFontLabel_normalitem_num:setScaleX(0.8000)
BitmapFontLabel_normalitem_num:setScaleY(0.8000)
BitmapFontLabel_normalitem_num:setColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_normalitem_num)
layout:setPositionPercentX(0.6712)
layout:setPositionPercentY(0.1723)
layout:setPercentWidth(0.3810)
layout:setPercentHeight(0.3048)
layout:setSize({width = 40.0000, height = 32.0000})
layout:setLeftMargin(70.4718)
layout:setRightMargin(-5.4718)
layout:setTopMargin(70.9065)
layout:setBottomMargin(2.0935)
Panel_1:addChild(BitmapFontLabel_normalitem_num)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

