--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(92)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(46)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Panel_1)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/PhysicalPowerAlertLayer/ppalert_sprites.plist")
Image_bg:loadTexture("ppalert_bg.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(48)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(360.0000, 667.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5211)
layout:setPercentWidth(0.8250)
layout:setPercentHeight(0.4109)
layout:setSize({width = 594.0000, height = 526.0000})
layout:setLeftMargin(63.0000)
layout:setRightMargin(63.0000)
layout:setTopMargin(349.9999)
layout:setBottomMargin(404.0001)
Layer:addChild(Image_bg)

--Create ppalert_ppbg
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/PhysicalPowerAlertLayer/ppalert_sprites.plist")
local ppalert_ppbg = cc.Sprite:createWithSpriteFrameName("ppalert_ppbg.png")
ppalert_ppbg:setName("ppalert_ppbg")
ppalert_ppbg:setTag(49)
ppalert_ppbg:setCascadeColorEnabled(true)
ppalert_ppbg:setCascadeOpacityEnabled(true)
ppalert_ppbg:setPosition(303.7194, 302.0307)
layout = ccui.LayoutComponent:bindLayoutComponent(ppalert_ppbg)
layout:setPositionPercentX(0.5113)
layout:setPositionPercentY(0.5742)
layout:setPercentWidth(0.2609)
layout:setPercentHeight(0.2947)
layout:setSize({width = 155.0000, height = 155.0000})
layout:setLeftMargin(226.2194)
layout:setRightMargin(212.7806)
layout:setTopMargin(146.4693)
layout:setBottomMargin(224.5307)
ppalert_ppbg:setBlendFunc({src = 770, dst = 771})
Image_bg:addChild(ppalert_ppbg)

--Create BitmapFontLabel_pp_num
local BitmapFontLabel_pp_num = ccui.TextBMFont:create()
BitmapFontLabel_pp_num:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_pp_num:setString([[-1]])
BitmapFontLabel_pp_num:setLayoutComponentEnabled(true)
BitmapFontLabel_pp_num:setName("BitmapFontLabel_pp_num")
BitmapFontLabel_pp_num:setTag(52)
BitmapFontLabel_pp_num:setCascadeColorEnabled(true)
BitmapFontLabel_pp_num:setCascadeOpacityEnabled(true)
BitmapFontLabel_pp_num:setPosition(328.2994, 271.2468)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_pp_num)
layout:setPositionPercentX(0.5527)
layout:setPositionPercentY(0.5157)
layout:setPercentWidth(0.0623)
layout:setPercentHeight(0.0608)
layout:setSize({width = 37.0000, height = 32.0000})
layout:setLeftMargin(309.7994)
layout:setRightMargin(247.2006)
layout:setTopMargin(238.7532)
layout:setBottomMargin(255.2468)
Image_bg:addChild(BitmapFontLabel_pp_num)

--Create Button_pp_exit
local Button_pp_exit = ccui.Button:create()
Button_pp_exit:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/PhysicalPowerAlertLayer/ppalert_sprites.plist")
Button_pp_exit:loadTextureNormal("ppalert_quit.png",1)
Button_pp_exit:setTitleFontSize(14)
Button_pp_exit:setTitleColor({r = 65, g = 65, b = 70})
Button_pp_exit:setScale9Enabled(true)
Button_pp_exit:setCapInsets({x = 0, y = 0, width = 172, height = 70})
Button_pp_exit:setLayoutComponentEnabled(true)
Button_pp_exit:setName("Button_pp_exit")
Button_pp_exit:setTag(50)
Button_pp_exit:setCascadeColorEnabled(true)
Button_pp_exit:setCascadeOpacityEnabled(true)
Button_pp_exit:setPosition(201.8714, 108.8834)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_pp_exit)
layout:setPositionPercentX(0.3399)
layout:setPositionPercentY(0.2070)
layout:setPercentWidth(0.2896)
layout:setPercentHeight(0.1331)
layout:setSize({width = 172.0000, height = 70.0000})
layout:setLeftMargin(115.8714)
layout:setRightMargin(306.1286)
layout:setTopMargin(382.1166)
layout:setBottomMargin(73.8834)
Image_bg:addChild(Button_pp_exit)

--Create Button_pp_back
local Button_pp_back = ccui.Button:create()
Button_pp_back:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/PhysicalPowerAlertLayer/ppalert_sprites.plist")
Button_pp_back:loadTextureNormal("ppalert_back.png",1)
Button_pp_back:setTitleFontSize(14)
Button_pp_back:setTitleColor({r = 65, g = 65, b = 70})
Button_pp_back:setScale9Enabled(true)
Button_pp_back:setCapInsets({x = 0, y = 0, width = 172, height = 70})
Button_pp_back:setLayoutComponentEnabled(true)
Button_pp_back:setName("Button_pp_back")
Button_pp_back:setTag(51)
Button_pp_back:setCascadeColorEnabled(true)
Button_pp_back:setCascadeOpacityEnabled(true)
Button_pp_back:setPosition(428.4163, 110.7342)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_pp_back)
layout:setPositionPercentX(0.7212)
layout:setPositionPercentY(0.2105)
layout:setPercentWidth(0.2896)
layout:setPercentHeight(0.1331)
layout:setSize({width = 172.0000, height = 70.0000})
layout:setLeftMargin(342.4163)
layout:setRightMargin(79.5837)
layout:setTopMargin(380.2658)
layout:setBottomMargin(75.7342)
Image_bg:addChild(Button_pp_back)

--Create BitmapFontLabel_1
local BitmapFontLabel_1 = ccui.TextBMFont:create()
BitmapFontLabel_1:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_1:setString([[现在退出会消耗一个体力哦喵~]])
BitmapFontLabel_1:setLayoutComponentEnabled(true)
BitmapFontLabel_1:setName("BitmapFontLabel_1")
BitmapFontLabel_1:setTag(61)
BitmapFontLabel_1:setCascadeColorEnabled(true)
BitmapFontLabel_1:setCascadeOpacityEnabled(true)
BitmapFontLabel_1:setPosition(360.0000, 590.2324)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4611)
layout:setPercentWidth(0.6319)
layout:setPercentHeight(0.0250)
layout:setSize({width = 455.0000, height = 32.0000})
layout:setLeftMargin(132.5000)
layout:setRightMargin(132.5000)
layout:setTopMargin(673.7676)
layout:setBottomMargin(574.2324)
Layer:addChild(BitmapFontLabel_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

