--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create rank_invite_item_bg_1
local rank_invite_item_bg_1 = cc.Sprite:create("res/RankLayer/rank_invite_item_bg_mine.png")
rank_invite_item_bg_1:setName("rank_invite_item_bg_1")
rank_invite_item_bg_1:setTag(92)
rank_invite_item_bg_1:setCascadeColorEnabled(true)
rank_invite_item_bg_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_invite_item_bg_1)
layout:setSize({width = 433.0000, height = 125.0000})
layout:setLeftMargin(-216.5000)
layout:setRightMargin(-216.5000)
layout:setTopMargin(-62.5000)
layout:setBottomMargin(-62.5000)
rank_invite_item_bg_1:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_invite_item_bg_1)

--Create rank_user_icon_bg
local rank_user_icon_bg = cc.Sprite:create("res/RankLayer/rank_user_icon_bg_mine.png")
rank_user_icon_bg:setName("rank_user_icon_bg")
rank_user_icon_bg:setTag(93)
rank_user_icon_bg:setCascadeColorEnabled(true)
rank_user_icon_bg:setCascadeOpacityEnabled(true)
rank_user_icon_bg:setPosition(130.9990, 3.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_user_icon_bg)
layout:setSize({width = 104.0000, height = 104.0000})
layout:setLeftMargin(78.9990)
layout:setRightMargin(-182.9990)
layout:setTopMargin(-55.0000)
layout:setBottomMargin(-49.0000)
rank_user_icon_bg:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_user_icon_bg)

--Create rank_user_icon_custom
local rank_user_icon_custom = cc.Sprite:create("res/RankLayer/rank_user_icon_default.png")
rank_user_icon_custom:setName("rank_user_icon_custom")
rank_user_icon_custom:setTag(22)
rank_user_icon_custom:setCascadeColorEnabled(true)
rank_user_icon_custom:setCascadeOpacityEnabled(true)
rank_user_icon_custom:setPosition(131.0000, 3.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_user_icon_custom)
layout:setSize({width = 88.0000, height = 88.0000})
layout:setLeftMargin(87.0000)
layout:setRightMargin(-175.0000)
layout:setTopMargin(-47.0000)
layout:setBottomMargin(-41.0000)
rank_user_icon_custom:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_user_icon_custom)

--Create BitmapFontLabel_rankno
local BitmapFontLabel_rankno = ccui.TextBMFont:create()
BitmapFontLabel_rankno:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_rankno:setString([[1]])
BitmapFontLabel_rankno:setLayoutComponentEnabled(true)
BitmapFontLabel_rankno:setName("BitmapFontLabel_rankno")
BitmapFontLabel_rankno:setTag(95)
BitmapFontLabel_rankno:setCascadeColorEnabled(true)
BitmapFontLabel_rankno:setCascadeOpacityEnabled(true)
BitmapFontLabel_rankno:setAnchorPoint(1.0000, 0.5000)
BitmapFontLabel_rankno:setPosition(74.6400, 30.9992)
BitmapFontLabel_rankno:setColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_rankno)
layout:setSize({width = 20.0000, height = 32.0000})
layout:setLeftMargin(54.6400)
layout:setRightMargin(-74.6400)
layout:setTopMargin(-46.9992)
layout:setBottomMargin(14.9992)
Node:addChild(BitmapFontLabel_rankno)

--Create BitmapFontLabel_name
local BitmapFontLabel_name = ccui.TextBMFont:create()
BitmapFontLabel_name:setFntFile("Default/defaultBMFont.fnt")
BitmapFontLabel_name:setString([[------]])
BitmapFontLabel_name:setLayoutComponentEnabled(true)
BitmapFontLabel_name:setName("BitmapFontLabel_name")
BitmapFontLabel_name:setTag(96)
BitmapFontLabel_name:setCascadeColorEnabled(true)
BitmapFontLabel_name:setCascadeOpacityEnabled(true)
BitmapFontLabel_name:setAnchorPoint(1.0000, 0.5000)
BitmapFontLabel_name:setPosition(74.6400, -31.0000)
BitmapFontLabel_name:setScaleX(1.2000)
BitmapFontLabel_name:setScaleY(1.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_name)
layout:setSize({width = 50.0000, height = 36.0000})
layout:setLeftMargin(24.6400)
layout:setRightMargin(-74.6400)
layout:setTopMargin(13.0000)
layout:setBottomMargin(-49.0000)
Node:addChild(BitmapFontLabel_name)

--Create BitmapFontLabel_1
local BitmapFontLabel_1 = ccui.TextBMFont:create()
BitmapFontLabel_1:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_1:setString([[best:0]])
BitmapFontLabel_1:setLayoutComponentEnabled(true)
BitmapFontLabel_1:setName("BitmapFontLabel_1")
BitmapFontLabel_1:setTag(59)
BitmapFontLabel_1:setCascadeColorEnabled(true)
BitmapFontLabel_1:setCascadeOpacityEnabled(true)
BitmapFontLabel_1:setAnchorPoint(1.0000, 0.5000)
BitmapFontLabel_1:setPosition(74.6395, 0.0000)
BitmapFontLabel_1:setScaleX(0.9000)
BitmapFontLabel_1:setScaleY(0.9000)
BitmapFontLabel_1:setColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_1)
layout:setSize({width = 108.0000, height = 32.0000})
layout:setLeftMargin(-33.3605)
layout:setRightMargin(-74.6395)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(-16.0000)
Node:addChild(BitmapFontLabel_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

