--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create rank_invite_item_bg_1
local rank_invite_item_bg_1 = cc.Sprite:create("res/RankLayer/rank_invite_item_bg.png")
rank_invite_item_bg_1:setName("rank_invite_item_bg_1")
rank_invite_item_bg_1:setTag(92)
rank_invite_item_bg_1:setCascadeColorEnabled(true)
rank_invite_item_bg_1:setCascadeOpacityEnabled(true)
rank_invite_item_bg_1:setPosition(218.0011, 63.0009)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_invite_item_bg_1)
layout:setSize({width = 433.0000, height = 118.0000})
layout:setLeftMargin(1.5011)
layout:setRightMargin(-434.5011)
layout:setTopMargin(-122.0009)
layout:setBottomMargin(4.0009)
rank_invite_item_bg_1:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_invite_item_bg_1)

--Create BitmapFontLabel_rankno
local BitmapFontLabel_rankno = ccui.TextBMFont:create()
BitmapFontLabel_rankno:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_rankno:setString([[1]])
BitmapFontLabel_rankno:setLayoutComponentEnabled(true)
BitmapFontLabel_rankno:setName("BitmapFontLabel_rankno")
BitmapFontLabel_rankno:setTag(101)
BitmapFontLabel_rankno:setCascadeColorEnabled(true)
BitmapFontLabel_rankno:setCascadeOpacityEnabled(true)
BitmapFontLabel_rankno:setPosition(21.7150, 64.8015)
BitmapFontLabel_rankno:setScaleX(1.2000)
BitmapFontLabel_rankno:setScaleY(1.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_rankno)
layout:setSize({width = 20.0000, height = 32.0000})
layout:setLeftMargin(11.7150)
layout:setRightMargin(-31.7150)
layout:setTopMargin(-80.8015)
layout:setBottomMargin(48.8015)
Node:addChild(BitmapFontLabel_rankno)

--Create rank_label_no
local rank_label_no = cc.Sprite:create("res/RankLayer/rank_label_1.png")
rank_label_no:setName("rank_label_no")
rank_label_no:setTag(21)
rank_label_no:setCascadeColorEnabled(true)
rank_label_no:setCascadeOpacityEnabled(true)
rank_label_no:setPosition(27.9995, 91.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_label_no)
layout:setSize({width = 41.0000, height = 64.0000})
layout:setLeftMargin(7.4995)
layout:setRightMargin(-48.4995)
layout:setTopMargin(-123.0001)
layout:setBottomMargin(59.0001)
rank_label_no:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_label_no)

--Create rank_user_icon_bg
local rank_user_icon_bg = cc.Sprite:create("res/RankLayer/rank_user_icon_bg.png")
rank_user_icon_bg:setName("rank_user_icon_bg")
rank_user_icon_bg:setTag(102)
rank_user_icon_bg:setCascadeColorEnabled(true)
rank_user_icon_bg:setCascadeOpacityEnabled(true)
rank_user_icon_bg:setPosition(105.8090, 63.0009)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_user_icon_bg)
layout:setSize({width = 104.0000, height = 104.0000})
layout:setLeftMargin(53.8090)
layout:setRightMargin(-157.8090)
layout:setTopMargin(-115.0009)
layout:setBottomMargin(11.0009)
rank_user_icon_bg:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_user_icon_bg)

--Create rank_user_icon_custom
local rank_user_icon_custom = cc.Sprite:create("res/RankLayer/rank_user_icon_default.png")
rank_user_icon_custom:setName("rank_user_icon_custom")
rank_user_icon_custom:setTag(23)
rank_user_icon_custom:setCascadeColorEnabled(true)
rank_user_icon_custom:setCascadeOpacityEnabled(true)
rank_user_icon_custom:setPosition(105.8102, 63.0009)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_user_icon_custom)
layout:setSize({width = 88.0000, height = 88.0000})
layout:setLeftMargin(61.8102)
layout:setRightMargin(-149.8102)
layout:setTopMargin(-107.0009)
layout:setBottomMargin(19.0009)
rank_user_icon_custom:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_user_icon_custom)

--Create BitmapFontLabel_name
local BitmapFontLabel_name = ccui.TextBMFont:create()
BitmapFontLabel_name:setFntFile("Default/defaultBMFont.fnt")
BitmapFontLabel_name:setString([[zzx]])
BitmapFontLabel_name:setLayoutComponentEnabled(true)
BitmapFontLabel_name:setName("BitmapFontLabel_name")
BitmapFontLabel_name:setTag(103)
BitmapFontLabel_name:setCascadeColorEnabled(true)
BitmapFontLabel_name:setCascadeOpacityEnabled(true)
BitmapFontLabel_name:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_name:setPosition(178.1109, 62.9032)
BitmapFontLabel_name:setScaleX(1.4000)
BitmapFontLabel_name:setScaleY(1.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_name)
layout:setSize({width = 41.0000, height = 36.0000})
layout:setLeftMargin(178.1109)
layout:setRightMargin(-219.1109)
layout:setTopMargin(-80.9032)
layout:setBottomMargin(44.9032)
Node:addChild(BitmapFontLabel_name)

--Create BitmapFontLabel_score_label
local BitmapFontLabel_score_label = ccui.TextBMFont:create()
BitmapFontLabel_score_label:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_score_label:setString([[best:]])
BitmapFontLabel_score_label:setLayoutComponentEnabled(true)
BitmapFontLabel_score_label:setName("BitmapFontLabel_score_label")
BitmapFontLabel_score_label:setTag(104)
BitmapFontLabel_score_label:setCascadeColorEnabled(true)
BitmapFontLabel_score_label:setCascadeOpacityEnabled(true)
BitmapFontLabel_score_label:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_score_label:setPosition(313.3177, 22.1857)
BitmapFontLabel_score_label:setScaleX(0.5000)
BitmapFontLabel_score_label:setScaleY(0.5000)
BitmapFontLabel_score_label:setColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_score_label)
layout:setSize({width = 86.0000, height = 32.0000})
layout:setLeftMargin(313.3177)
layout:setRightMargin(-399.3177)
layout:setTopMargin(-38.1857)
layout:setBottomMargin(6.1857)
Node:addChild(BitmapFontLabel_score_label)

--Create BitmapFontLabel_score
local BitmapFontLabel_score = ccui.TextBMFont:create()
BitmapFontLabel_score:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_score:setString([[0]])
BitmapFontLabel_score:setLayoutComponentEnabled(true)
BitmapFontLabel_score:setName("BitmapFontLabel_score")
BitmapFontLabel_score:setTag(105)
BitmapFontLabel_score:setCascadeColorEnabled(true)
BitmapFontLabel_score:setCascadeOpacityEnabled(true)
BitmapFontLabel_score:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_score:setPosition(360.5812, 22.1806)
BitmapFontLabel_score:setScaleX(0.5000)
BitmapFontLabel_score:setScaleY(0.5000)
BitmapFontLabel_score:setColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_score)
layout:setSize({width = 23.0000, height = 32.0000})
layout:setLeftMargin(360.5812)
layout:setRightMargin(-383.5812)
layout:setTopMargin(-38.1806)
layout:setBottomMargin(6.1806)
Node:addChild(BitmapFontLabel_score)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

