--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create pass_1
local pass_1 = cc.Sprite:create("res.2/General/General_bg.png")
pass_1:setName("pass_1")
pass_1:setTag(59)
pass_1:setCascadeColorEnabled(true)
pass_1:setCascadeOpacityEnabled(true)
pass_1:setPosition(361.2899, 636.5199)
layout = ccui.LayoutComponent:bindLayoutComponent(pass_1)
layout:setPositionPercentX(0.5018)
layout:setPositionPercentY(0.4973)
layout:setPercentWidth(0.7417)
layout:setPercentHeight(0.6508)
layout:setSize({width = 534.0000, height = 833.0000})
layout:setLeftMargin(94.2899)
layout:setRightMargin(91.7101)
layout:setTopMargin(226.9801)
layout:setBottomMargin(220.0199)
pass_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(pass_1)

--Create BitmapFontLabel_title
local BitmapFontLabel_title = ccui.TextBMFont:create()
BitmapFontLabel_title:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_title:setString([[第1关]])
BitmapFontLabel_title:setLayoutComponentEnabled(true)
BitmapFontLabel_title:setName("BitmapFontLabel_title")
BitmapFontLabel_title:setTag(106)
BitmapFontLabel_title:setCascadeColorEnabled(true)
BitmapFontLabel_title:setCascadeOpacityEnabled(true)
BitmapFontLabel_title:setPosition(197.0627, 979.9254)
BitmapFontLabel_title:setScaleX(1.5000)
BitmapFontLabel_title:setScaleY(1.5000)
BitmapFontLabel_title:setColor({r = 0, g = 128, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_title)
layout:setPositionPercentX(0.2737)
layout:setPositionPercentY(0.7656)
layout:setPercentWidth(0.1194)
layout:setPercentHeight(0.0250)
layout:setSize({width = 86.0000, height = 32.0000})
layout:setLeftMargin(154.0627)
layout:setRightMargin(479.9373)
layout:setTopMargin(284.0746)
layout:setBottomMargin(963.9254)
Layer:addChild(BitmapFontLabel_title)

--Create BitmapFontLabel_1
local BitmapFontLabel_1 = ccui.TextBMFont:create()
BitmapFontLabel_1:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_1:setString([[奖励清单]])
BitmapFontLabel_1:setLayoutComponentEnabled(true)
BitmapFontLabel_1:setName("BitmapFontLabel_1")
BitmapFontLabel_1:setTag(122)
BitmapFontLabel_1:setCascadeColorEnabled(true)
BitmapFontLabel_1:setCascadeOpacityEnabled(true)
BitmapFontLabel_1:setPosition(360.0000, 898.2758)
BitmapFontLabel_1:setColor({r = 203, g = 91, b = 52})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7018)
layout:setPercentWidth(0.1889)
layout:setPercentHeight(0.0250)
layout:setSize({width = 136.0000, height = 32.0000})
layout:setLeftMargin(292.0000)
layout:setRightMargin(292.0000)
layout:setTopMargin(365.7242)
layout:setBottomMargin(882.2758)
Layer:addChild(BitmapFontLabel_1)

--Create General_gree_line_1
local General_gree_line_1 = cc.Sprite:create("res.2/General/General_gree_line.png")
General_gree_line_1:setName("General_gree_line_1")
General_gree_line_1:setTag(202)
General_gree_line_1:setCascadeColorEnabled(true)
General_gree_line_1:setCascadeOpacityEnabled(true)
General_gree_line_1:setPosition(264.3056, 941.9615)
layout = ccui.LayoutComponent:bindLayoutComponent(General_gree_line_1)
layout:setPositionPercentX(0.3671)
layout:setPositionPercentY(0.7359)
layout:setPercentWidth(0.4472)
layout:setPercentHeight(0.0047)
layout:setSize({width = 322.0000, height = 6.0000})
layout:setLeftMargin(103.3056)
layout:setRightMargin(294.6944)
layout:setTopMargin(335.0385)
layout:setBottomMargin(938.9615)
General_gree_line_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(General_gree_line_1)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setDirection(1)
ListView_1:setGravity(2)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorType(1)
ListView_1:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_1:setBackGroundColorOpacity(0)
ListView_1:setTouchEnabled(false);
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(123)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setAnchorPoint(0.5000, 0.5000)
ListView_1:setPosition(360.0001, 632.1246)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4938)
layout:setPercentWidth(0.6944)
layout:setPercentHeight(0.3125)
layout:setSize({width = 500.0000, height = 400.0000})
layout:setLeftMargin(110.0001)
layout:setRightMargin(109.9999)
layout:setTopMargin(447.8754)
layout:setBottomMargin(432.1246)
Layer:addChild(ListView_1)

--Create Button_win_lose
local Button_win_lose = ccui.Button:create()
Button_win_lose:ignoreContentAdaptWithSize(false)
Button_win_lose:loadTextureNormal("res.2/General/General_close.png",0)
Button_win_lose:setTitleFontSize(14)
Button_win_lose:setTitleColor({r = 65, g = 65, b = 70})
Button_win_lose:setScale9Enabled(true)
Button_win_lose:setCapInsets({x = 28, y = 30, width = 27, height = 24})
Button_win_lose:setLayoutComponentEnabled(true)
Button_win_lose:setName("Button_win_lose")
Button_win_lose:setTag(64)
Button_win_lose:setCascadeColorEnabled(true)
Button_win_lose:setCascadeOpacityEnabled(true)
Button_win_lose:setPosition(565.7201, 991.3126)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_win_lose)
layout:setPositionPercentX(0.7857)
layout:setPositionPercentY(0.7745)
layout:setPercentWidth(0.1153)
layout:setPercentHeight(0.0656)
layout:setSize({width = 83.0000, height = 84.0000})
layout:setLeftMargin(524.2201)
layout:setRightMargin(112.7799)
layout:setTopMargin(246.6874)
layout:setBottomMargin(949.3126)
Layer:addChild(Button_win_lose)

--Create Button_win_next
local Button_win_next = ccui.Button:create()
Button_win_next:ignoreContentAdaptWithSize(false)
Button_win_next:loadTextureNormal("res.2/gameWinLayer/gamewin_next.png",0)
Button_win_next:setTitleFontSize(14)
Button_win_next:setTitleColor({r = 65, g = 65, b = 70})
Button_win_next:setScale9Enabled(true)
Button_win_next:setCapInsets({x = 21, y = 0, width = 54, height = 97})
Button_win_next:setLayoutComponentEnabled(true)
Button_win_next:setName("Button_win_next")
Button_win_next:setTag(66)
Button_win_next:setCascadeColorEnabled(true)
Button_win_next:setCascadeOpacityEnabled(true)
Button_win_next:setPosition(360.0000, 320.6801)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_win_next)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2505)
layout:setPercentWidth(0.1333)
layout:setPercentHeight(0.0758)
layout:setSize({width = 96.0000, height = 97.0000})
layout:setLeftMargin(312.0000)
layout:setRightMargin(312.0000)
layout:setTopMargin(910.8199)
layout:setBottomMargin(272.1801)
Layer:addChild(Button_win_next)

--Create gametask_line_2
local gametask_line_2 = cc.Sprite:create("res.2/GameTaskLayer/gametask_line.png")
gametask_line_2:setName("gametask_line_2")
gametask_line_2:setTag(203)
gametask_line_2:setCascadeColorEnabled(true)
gametask_line_2:setCascadeOpacityEnabled(true)
gametask_line_2:setPosition(360.0000, 851.0670)
layout = ccui.LayoutComponent:bindLayoutComponent(gametask_line_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6649)
layout:setPercentWidth(0.6375)
layout:setPercentHeight(0.0047)
layout:setSize({width = 459.0000, height = 6.0000})
layout:setLeftMargin(130.5000)
layout:setRightMargin(130.5000)
layout:setTopMargin(425.9330)
layout:setBottomMargin(848.0670)
gametask_line_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(gametask_line_2)

--Create gametask_line_3
local gametask_line_3 = cc.Sprite:create("res.2/GameTaskLayer/gametask_line.png")
gametask_line_3:setName("gametask_line_3")
gametask_line_3:setTag(204)
gametask_line_3:setCascadeColorEnabled(true)
gametask_line_3:setCascadeOpacityEnabled(true)
gametask_line_3:setPosition(360.0000, 401.4624)
layout = ccui.LayoutComponent:bindLayoutComponent(gametask_line_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3136)
layout:setPercentWidth(0.6375)
layout:setPercentHeight(0.0047)
layout:setSize({width = 459.0000, height = 6.0000})
layout:setLeftMargin(130.5000)
layout:setRightMargin(130.5000)
layout:setTopMargin(875.5376)
layout:setBottomMargin(398.4624)
gametask_line_3:setBlendFunc({src = 1, dst = 771})
Layer:addChild(gametask_line_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

