--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.ImageView:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:loadTexture("res.2/gameWinLayer/gamewin_gift_item_bg.png",0)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(225)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(0.0000, 0.0013)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 399.0000, height = 82.0000})
layout:setLeftMargin(-199.5000)
layout:setRightMargin(-199.5000)
layout:setTopMargin(-41.0013)
layout:setBottomMargin(-40.9987)
Node:addChild(Panel_1)

--Create sprite_taskitem_icon
cc.SpriteFrameCache:getInstance():addSpriteFrames("res/GameOverLayer/gameoverlayer_sprites.plist")
local sprite_taskitem_icon = cc.Sprite:createWithSpriteFrameName("over_fish_0.png")
sprite_taskitem_icon:setName("sprite_taskitem_icon")
sprite_taskitem_icon:setTag(84)
sprite_taskitem_icon:setCascadeColorEnabled(true)
sprite_taskitem_icon:setCascadeOpacityEnabled(true)
sprite_taskitem_icon:setPosition(53.6436, 41.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite_taskitem_icon)
layout:setPositionPercentX(0.1344)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1153)
layout:setPercentHeight(0.6829)
layout:setSize({width = 46.0000, height = 56.0000})
layout:setLeftMargin(30.6436)
layout:setRightMargin(322.3564)
layout:setTopMargin(13.0000)
layout:setBottomMargin(13.0000)
sprite_taskitem_icon:setBlendFunc({src = 770, dst = 771})
Panel_1:addChild(sprite_taskitem_icon)

--Create BitmapFontLabel_taskitem_num
local BitmapFontLabel_taskitem_num = ccui.TextBMFont:create()
BitmapFontLabel_taskitem_num:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_taskitem_num:setString([[x0]])
BitmapFontLabel_taskitem_num:setLayoutComponentEnabled(true)
BitmapFontLabel_taskitem_num:setName("BitmapFontLabel_taskitem_num")
BitmapFontLabel_taskitem_num:setTag(85)
BitmapFontLabel_taskitem_num:setCascadeColorEnabled(true)
BitmapFontLabel_taskitem_num:setCascadeOpacityEnabled(true)
BitmapFontLabel_taskitem_num:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_taskitem_num:setPosition(284.0413, 41.0000)
BitmapFontLabel_taskitem_num:setScaleX(0.8000)
BitmapFontLabel_taskitem_num:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_taskitem_num)
layout:setPositionPercentX(0.7119)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1003)
layout:setPercentHeight(0.3902)
layout:setSize({width = 40.0000, height = 32.0000})
layout:setLeftMargin(284.0413)
layout:setRightMargin(74.9587)
layout:setTopMargin(25.0000)
layout:setBottomMargin(25.0000)
Panel_1:addChild(BitmapFontLabel_taskitem_num)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

