--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create BitmapFontLabel_rankno
local BitmapFontLabel_rankno = ccui.TextBMFont:create()
BitmapFontLabel_rankno:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_rankno:setString([[1]])
BitmapFontLabel_rankno:setLayoutComponentEnabled(true)
BitmapFontLabel_rankno:setName("BitmapFontLabel_rankno")
BitmapFontLabel_rankno:setTag(101)
BitmapFontLabel_rankno:setCascadeColorEnabled(true)
BitmapFontLabel_rankno:setCascadeOpacityEnabled(true)
BitmapFontLabel_rankno:setPosition(35.2153, 46.8148)
BitmapFontLabel_rankno:setScaleX(1.2000)
BitmapFontLabel_rankno:setScaleY(1.2000)
BitmapFontLabel_rankno:setColor({r = 177, g = 97, b = 37})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_rankno)
layout:setSize({width = 20.0000, height = 32.0000})
layout:setLeftMargin(25.2153)
layout:setRightMargin(-45.2153)
layout:setTopMargin(-62.8148)
layout:setBottomMargin(30.8148)
Node:addChild(BitmapFontLabel_rankno)

--Create rank_list_item_bg_5
local rank_list_item_bg_5 = cc.Sprite:create("res.2/RankLayer/rank_list_item_bg.png")
rank_list_item_bg_5:setName("rank_list_item_bg_5")
rank_list_item_bg_5:setTag(141)
rank_list_item_bg_5:setCascadeColorEnabled(true)
rank_list_item_bg_5:setCascadeOpacityEnabled(true)
rank_list_item_bg_5:setPosition(232.1873, 46.9348)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_list_item_bg_5)
layout:setSize({width = 228.0000, height = 52.0000})
layout:setLeftMargin(118.1873)
layout:setRightMargin(-346.1873)
layout:setTopMargin(-72.9348)
layout:setBottomMargin(20.9348)
rank_list_item_bg_5:setBlendFunc({src = 1, dst = 771})
Node:addChild(rank_list_item_bg_5)

--Create rank_user_icon_bg
local rank_user_icon_bg = cc.Sprite:create("res.2/RankLayer/rank_list_usericon_bg.png")
rank_user_icon_bg:setName("rank_user_icon_bg")
rank_user_icon_bg:setTag(102)
rank_user_icon_bg:setCascadeColorEnabled(true)
rank_user_icon_bg:setCascadeOpacityEnabled(true)
rank_user_icon_bg:setPosition(119.3104, 56.9354)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_user_icon_bg)
layout:setSize({width = 88.0000, height = 86.0000})
layout:setLeftMargin(75.3104)
layout:setRightMargin(-163.3104)
layout:setTopMargin(-99.9354)
layout:setBottomMargin(13.9354)
rank_user_icon_bg:setBlendFunc({src = 1, dst = 771})
Node:addChild(rank_user_icon_bg)

--Create rank_user_icon_custom
local rank_user_icon_custom = cc.Sprite:create("res/RankLayer/rank_user_icon_default.png")
rank_user_icon_custom:setName("rank_user_icon_custom")
rank_user_icon_custom:setTag(23)
rank_user_icon_custom:setCascadeColorEnabled(true)
rank_user_icon_custom:setCascadeOpacityEnabled(true)
rank_user_icon_custom:setPosition(119.3143, 56.9345)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_user_icon_custom)
layout:setSize({width = 88.0000, height = 88.0000})
layout:setLeftMargin(75.3143)
layout:setRightMargin(-163.3143)
layout:setTopMargin(-100.9345)
layout:setBottomMargin(12.9345)
rank_user_icon_custom:setBlendFunc({src = 770, dst = 771})
Node:addChild(rank_user_icon_custom)

--Create BitmapFontLabel_name
local BitmapFontLabel_name = ccui.TextBMFont:create()
BitmapFontLabel_name:setString([[zzx]])
BitmapFontLabel_name:setLayoutComponentEnabled(true)
BitmapFontLabel_name:setName("BitmapFontLabel_name")
BitmapFontLabel_name:setTag(103)
BitmapFontLabel_name:setCascadeColorEnabled(true)
BitmapFontLabel_name:setCascadeOpacityEnabled(true)
BitmapFontLabel_name:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_name:setPosition(191.6126, 44.9160)
BitmapFontLabel_name:setScaleX(1.4000)
BitmapFontLabel_name:setScaleY(1.4000)
BitmapFontLabel_name:setColor({r = 172, g = 92, b = 45})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_name)
layout:setSize({width = 15.0000, height = 15.0000})
layout:setLeftMargin(191.6126)
layout:setRightMargin(-206.6126)
layout:setTopMargin(-52.4160)
layout:setBottomMargin(37.4160)
Node:addChild(BitmapFontLabel_name)

--Create BitmapFontLabel_score_label
local BitmapFontLabel_score_label = ccui.TextBMFont:create()
BitmapFontLabel_score_label:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_score_label:setString([[best:]])
BitmapFontLabel_score_label:setLayoutComponentEnabled(true)
BitmapFontLabel_score_label:setName("BitmapFontLabel_score_label")
BitmapFontLabel_score_label:setTag(104)
BitmapFontLabel_score_label:setCascadeColorEnabled(true)
BitmapFontLabel_score_label:setCascadeOpacityEnabled(true)
BitmapFontLabel_score_label:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_score_label:setPosition(352.6588, 46.0366)
BitmapFontLabel_score_label:setScaleX(0.5000)
BitmapFontLabel_score_label:setScaleY(0.5000)
BitmapFontLabel_score_label:setColor({r = 175, g = 99, b = 38})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_score_label)
layout:setSize({width = 86.0000, height = 32.0000})
layout:setLeftMargin(352.6588)
layout:setRightMargin(-438.6588)
layout:setTopMargin(-62.0366)
layout:setBottomMargin(30.0366)
Node:addChild(BitmapFontLabel_score_label)

--Create BitmapFontLabel_score
local BitmapFontLabel_score = ccui.TextBMFont:create()
BitmapFontLabel_score:setFntFile("res/GamingLayer/icroncatFont.fnt")
BitmapFontLabel_score:setString([[0]])
BitmapFontLabel_score:setLayoutComponentEnabled(true)
BitmapFontLabel_score:setName("BitmapFontLabel_score")
BitmapFontLabel_score:setTag(105)
BitmapFontLabel_score:setCascadeColorEnabled(true)
BitmapFontLabel_score:setCascadeOpacityEnabled(true)
BitmapFontLabel_score:setAnchorPoint(0.0000, 0.5000)
BitmapFontLabel_score:setPosition(399.9232, 46.0308)
BitmapFontLabel_score:setScaleX(0.5000)
BitmapFontLabel_score:setScaleY(0.5000)
BitmapFontLabel_score:setColor({r = 175, g = 99, b = 38})
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_score)
layout:setSize({width = 23.0000, height = 32.0000})
layout:setLeftMargin(399.9232)
layout:setRightMargin(-422.9232)
layout:setTopMargin(-62.0308)
layout:setBottomMargin(30.0308)
Node:addChild(BitmapFontLabel_score)

--Create rank_line_7
local rank_line_7 = cc.Sprite:create("res.2/RankLayer/rank_line.png")
rank_line_7:setName("rank_line_7")
rank_line_7:setTag(143)
rank_line_7:setCascadeColorEnabled(true)
rank_line_7:setCascadeOpacityEnabled(true)
rank_line_7:setPosition(232.1852, 3.0901)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_line_7)
layout:setSize({width = 459.0000, height = 6.0000})
layout:setLeftMargin(2.6852)
layout:setRightMargin(-461.6852)
layout:setTopMargin(-6.0901)
layout:setBottomMargin(0.0901)
rank_line_7:setBlendFunc({src = 1, dst = 771})
Node:addChild(rank_line_7)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

