--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(144)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(55)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Panel_1)

--Create rank_bg_1
local rank_bg_1 = cc.Sprite:create("res.2/General/General_bg.png")
rank_bg_1:setName("rank_bg_1")
rank_bg_1:setTag(56)
rank_bg_1:setCascadeColorEnabled(true)
rank_bg_1:setCascadeOpacityEnabled(true)
rank_bg_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_bg_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7417)
layout:setPercentHeight(0.6508)
layout:setSize({width = 534.0000, height = 833.0000})
layout:setLeftMargin(93.0000)
layout:setRightMargin(93.0000)
layout:setTopMargin(223.5000)
layout:setBottomMargin(223.5000)
rank_bg_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(rank_bg_1)

--Create rank_title_rank_1
local rank_title_rank_1 = cc.Sprite:create("res.2/RankLayer/rank_title_rank.png")
rank_title_rank_1:setName("rank_title_rank_1")
rank_title_rank_1:setTag(87)
rank_title_rank_1:setCascadeColorEnabled(true)
rank_title_rank_1:setCascadeOpacityEnabled(true)
rank_title_rank_1:setPosition(175.3885, 744.7437)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_title_rank_1)
layout:setPositionPercentX(0.3284)
layout:setPositionPercentY(0.8941)
layout:setPercentWidth(0.6086)
layout:setPercentHeight(0.0912)
layout:setSize({width = 325.0000, height = 76.0000})
layout:setLeftMargin(12.8885)
layout:setRightMargin(196.1115)
layout:setTopMargin(50.2563)
layout:setBottomMargin(706.7437)
rank_title_rank_1:setBlendFunc({src = 1, dst = 771})
rank_bg_1:addChild(rank_title_rank_1)

--Create Button_rank_close
local Button_rank_close = ccui.Button:create()
Button_rank_close:ignoreContentAdaptWithSize(false)
Button_rank_close:loadTextureNormal("res.2/General/General_close.png",0)
Button_rank_close:setTitleFontSize(14)
Button_rank_close:setTitleColor({r = 65, g = 65, b = 70})
Button_rank_close:setScale9Enabled(true)
Button_rank_close:setCapInsets({x = 15, y = 11, width = 53, height = 62})
Button_rank_close:setLayoutComponentEnabled(true)
Button_rank_close:setName("Button_rank_close")
Button_rank_close:setTag(57)
Button_rank_close:setCascadeColorEnabled(true)
Button_rank_close:setCascadeOpacityEnabled(true)
Button_rank_close:setPosition(469.2642, 776.6029)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_rank_close)
layout:setPositionPercentX(0.8788)
layout:setPositionPercentY(0.9323)
layout:setPercentWidth(0.1554)
layout:setPercentHeight(0.1008)
layout:setSize({width = 83.0000, height = 84.0000})
layout:setLeftMargin(427.7642)
layout:setRightMargin(23.2358)
layout:setTopMargin(14.3971)
layout:setBottomMargin(734.6029)
rank_bg_1:addChild(Button_rank_close)

--Create Panel_connect
local Panel_connect = ccui.Layout:create()
Panel_connect:ignoreContentAdaptWithSize(false)
Panel_connect:setClippingEnabled(false)
Panel_connect:setBackGroundColorType(1)
Panel_connect:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_connect:setBackGroundColorOpacity(0)
Panel_connect:setTouchEnabled(true);
Panel_connect:setLayoutComponentEnabled(true)
Panel_connect:setName("Panel_connect")
Panel_connect:setTag(86)
Panel_connect:setCascadeColorEnabled(true)
Panel_connect:setCascadeOpacityEnabled(true)
Panel_connect:setAnchorPoint(0.5000, 0.5000)
Panel_connect:setPosition(248.1980, 436.8131)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_connect)
layout:setPositionPercentX(0.4648)
layout:setPositionPercentY(0.5244)
layout:setPercentWidth(0.3745)
layout:setPercentHeight(0.2401)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(148.1980)
layout:setRightMargin(185.8020)
layout:setTopMargin(296.1869)
layout:setBottomMargin(336.8131)
rank_bg_1:addChild(Panel_connect)

--Create rank_title
local rank_title = cc.Sprite:create("res.2/RankLayer/rank_label_1.png")
rank_title:setName("rank_title")
rank_title:setTag(80)
rank_title:setCascadeColorEnabled(true)
rank_title:setCascadeOpacityEnabled(true)
rank_title:setPosition(117.7617, 132.6323)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_title)
layout:setPositionPercentX(0.5888)
layout:setPositionPercentY(0.6632)
layout:setPercentWidth(2.0500)
layout:setPercentHeight(0.5200)
layout:setSize({width = 410.0000, height = 104.0000})
layout:setLeftMargin(-87.2383)
layout:setRightMargin(-122.7617)
layout:setTopMargin(15.3677)
layout:setBottomMargin(80.6323)
rank_title:setBlendFunc({src = 1, dst = 771})
Panel_connect:addChild(rank_title)

--Create Button_connect_facebook
local Button_connect_facebook = ccui.Button:create()
Button_connect_facebook:ignoreContentAdaptWithSize(false)
Button_connect_facebook:loadTextureNormal("res.2/RankLayer/rank_btn_connect.png",0)
Button_connect_facebook:setTitleFontSize(14)
Button_connect_facebook:setTitleColor({r = 65, g = 65, b = 70})
Button_connect_facebook:setScale9Enabled(true)
Button_connect_facebook:setCapInsets({x = 15, y = 11, width = 318, height = 99})
Button_connect_facebook:setLayoutComponentEnabled(true)
Button_connect_facebook:setName("Button_connect_facebook")
Button_connect_facebook:setTag(88)
Button_connect_facebook:setCascadeColorEnabled(true)
Button_connect_facebook:setCascadeOpacityEnabled(true)
Button_connect_facebook:setPosition(119.0106, -53.6724)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_connect_facebook)
layout:setPositionPercentX(0.5951)
layout:setPositionPercentY(-0.2684)
layout:setPercentWidth(1.7400)
layout:setPercentHeight(0.6050)
layout:setSize({width = 348.0000, height = 121.0000})
layout:setLeftMargin(-54.9894)
layout:setRightMargin(-93.0106)
layout:setTopMargin(193.1724)
layout:setBottomMargin(-114.1724)
Panel_connect:addChild(Button_connect_facebook)

--Create Panel_rank
local Panel_rank = ccui.Layout:create()
Panel_rank:ignoreContentAdaptWithSize(false)
Panel_rank:setClippingEnabled(false)
Panel_rank:setBackGroundColorType(1)
Panel_rank:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_rank:setBackGroundColorOpacity(0)
Panel_rank:setTouchEnabled(true);
Panel_rank:setLayoutComponentEnabled(true)
Panel_rank:setName("Panel_rank")
Panel_rank:setTag(98)
Panel_rank:setCascadeColorEnabled(true)
Panel_rank:setCascadeOpacityEnabled(true)
Panel_rank:setPosition(157.1796, 300.8863)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_rank)
layout:setPositionPercentX(0.2943)
layout:setPositionPercentY(0.3612)
layout:setPercentWidth(0.3745)
layout:setPercentHeight(0.2401)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(157.1796)
layout:setRightMargin(176.8204)
layout:setTopMargin(332.1137)
layout:setBottomMargin(300.8863)
rank_bg_1:addChild(Panel_rank)

--Create Button_invite_facebook
local Button_invite_facebook = ccui.Button:create()
Button_invite_facebook:ignoreContentAdaptWithSize(false)
Button_invite_facebook:loadTextureNormal("res.2/RankLayer/rank_btn_invite.png",0)
Button_invite_facebook:setTitleFontSize(14)
Button_invite_facebook:setTitleColor({r = 65, g = 65, b = 70})
Button_invite_facebook:setScale9Enabled(true)
Button_invite_facebook:setCapInsets({x = 15, y = 11, width = 257, height = 79})
Button_invite_facebook:setLayoutComponentEnabled(true)
Button_invite_facebook:setName("Button_invite_facebook")
Button_invite_facebook:setTag(100)
Button_invite_facebook:setCascadeColorEnabled(true)
Button_invite_facebook:setCascadeOpacityEnabled(true)
Button_invite_facebook:setPosition(108.6585, 331.2654)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_invite_facebook)
layout:setPositionPercentX(0.5433)
layout:setPositionPercentY(1.6563)
layout:setPercentWidth(1.4350)
layout:setPercentHeight(0.5050)
layout:setSize({width = 287.0000, height = 101.0000})
layout:setLeftMargin(-34.8415)
layout:setRightMargin(-52.1585)
layout:setTopMargin(-181.7654)
layout:setBottomMargin(280.7654)
Panel_rank:addChild(Button_invite_facebook)

--Create rank_line_3
local rank_line_3 = cc.Sprite:create("res.2/RankLayer/rank_line.png")
rank_line_3:setName("rank_line_3")
rank_line_3:setTag(101)
rank_line_3:setCascadeColorEnabled(true)
rank_line_3:setCascadeOpacityEnabled(true)
rank_line_3:setPosition(112.9391, 252.3630)
layout = ccui.LayoutComponent:bindLayoutComponent(rank_line_3)
layout:setPositionPercentX(0.5647)
layout:setPositionPercentY(1.2618)
layout:setPercentWidth(2.2950)
layout:setPercentHeight(0.0300)
layout:setSize({width = 459.0000, height = 6.0000})
layout:setLeftMargin(-116.5609)
layout:setRightMargin(-142.4391)
layout:setTopMargin(-55.3630)
layout:setBottomMargin(249.3630)
rank_line_3:setBlendFunc({src = 1, dst = 771})
Panel_rank:addChild(rank_line_3)

--Create ListView_rank
local ListView_rank = ccui.ListView:create()
ListView_rank:setDirection(1)
ListView_rank:setGravity(2)
ListView_rank:ignoreContentAdaptWithSize(false)
ListView_rank:setClippingEnabled(true)
ListView_rank:setBackGroundColorType(1)
ListView_rank:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_rank:setBackGroundColorOpacity(0)
ListView_rank:setLayoutComponentEnabled(true)
ListView_rank:setName("ListView_rank")
ListView_rank:setTag(102)
ListView_rank:setCascadeColorEnabled(true)
ListView_rank:setCascadeOpacityEnabled(true)
ListView_rank:setAnchorPoint(0.5000, 0.5000)
ListView_rank:setPosition(115.6600, 23.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_rank)
layout:setPositionPercentX(0.5783)
layout:setPositionPercentY(0.1170)
layout:setPercentWidth(2.2500)
layout:setPercentHeight(2.2500)
layout:setSize({width = 450.0000, height = 450.0000})
layout:setLeftMargin(-109.3400)
layout:setRightMargin(-140.6600)
layout:setTopMargin(-48.4000)
layout:setBottomMargin(-201.6000)
Panel_rank:addChild(ListView_rank)

--Create Slider_rank
local Slider_rank = ccui.Slider:create()
Slider_rank:ignoreContentAdaptWithSize(false)
Slider_rank:loadBarTexture("res.2/RankLayer/rank_list_line.png",0)
Slider_rank:loadProgressBarTexture("res.2/RankLayer/rank_list_line.png",0)
Slider_rank:loadSlidBallTextureNormal("res.2/RankLayer/rank_list_cursor.png",0)
Slider_rank:loadSlidBallTexturePressed("res.2/RankLayer/rank_list_cursor.png",0)
Slider_rank:loadSlidBallTextureDisabled("res.2/RankLayer/rank_list_cursor.png",0)
Slider_rank:setPercent(5)
Slider_rank:setLayoutComponentEnabled(true)
Slider_rank:setName("Slider_rank")
Slider_rank:setTag(13)
Slider_rank:setCascadeColorEnabled(true)
Slider_rank:setCascadeOpacityEnabled(true)
Slider_rank:setPosition(351.4166, 23.4449)
Slider_rank:setRotationSkewX(90.0000)
Slider_rank:setRotationSkewY(90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Slider_rank)
layout:setPositionPercentX(1.7571)
layout:setPositionPercentY(0.1172)
layout:setPercentWidth(2.5650)
layout:setPercentHeight(0.0600)
layout:setSize({width = 513.0000, height = 12.0000})
layout:setLeftMargin(94.9166)
layout:setRightMargin(-407.9166)
layout:setTopMargin(170.5551)
layout:setBottomMargin(17.4449)
Panel_rank:addChild(Slider_rank)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

