--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Panel_share_bg
local Panel_share_bg = ccui.Layout:create()
Panel_share_bg:ignoreContentAdaptWithSize(false)
Panel_share_bg:setClippingEnabled(false)
Panel_share_bg:setBackGroundColorType(1)
Panel_share_bg:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_share_bg:setBackGroundColorOpacity(50)
Panel_share_bg:setTouchEnabled(true);
Panel_share_bg:setLayoutComponentEnabled(true)
Panel_share_bg:setName("Panel_share_bg")
Panel_share_bg:setTag(69)
Panel_share_bg:setCascadeColorEnabled(true)
Panel_share_bg:setCascadeOpacityEnabled(true)
Panel_share_bg:setAnchorPoint(0.5000, 0.5000)
Panel_share_bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_share_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Panel_share_bg)

--Create share_bg
local share_bg = cc.Sprite:create("res.2/share/share_bg.png")
share_bg:setName("share_bg")
share_bg:setTag(70)
share_bg:setCascadeColorEnabled(true)
share_bg:setCascadeOpacityEnabled(true)
share_bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(share_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7833)
layout:setPercentHeight(0.3586)
layout:setSize({width = 564.0000, height = 459.0000})
layout:setLeftMargin(78.0000)
layout:setRightMargin(78.0000)
layout:setTopMargin(410.5000)
layout:setBottomMargin(410.5000)
share_bg:setBlendFunc({src = 1, dst = 771})
Layer:addChild(share_bg)

--Create share_title
local share_title = cc.Sprite:create("res.2/share/share_title.png")
share_title:setName("share_title")
share_title:setTag(72)
share_title:setCascadeColorEnabled(true)
share_title:setCascadeOpacityEnabled(true)
share_title:setPosition(187.5719, 359.3942)
layout = ccui.LayoutComponent:bindLayoutComponent(share_title)
layout:setPositionPercentX(0.3326)
layout:setPositionPercentY(0.7830)
layout:setPercentWidth(0.5762)
layout:setPercentHeight(0.1612)
layout:setSize({width = 325.0000, height = 74.0000})
layout:setLeftMargin(25.0719)
layout:setRightMargin(213.9281)
layout:setTopMargin(62.6058)
layout:setBottomMargin(322.3942)
share_title:setBlendFunc({src = 1, dst = 771})
share_bg:addChild(share_title)

--Create Button_share_close
local Button_share_close = ccui.Button:create()
Button_share_close:ignoreContentAdaptWithSize(false)
Button_share_close:loadTextureNormal("res.2/General/General_close.png",0)
Button_share_close:setTitleFontSize(14)
Button_share_close:setTitleColor({r = 65, g = 65, b = 70})
Button_share_close:setScale9Enabled(true)
Button_share_close:setCapInsets({x = 15, y = 11, width = 53, height = 62})
Button_share_close:setLayoutComponentEnabled(true)
Button_share_close:setName("Button_share_close")
Button_share_close:setTag(71)
Button_share_close:setCascadeColorEnabled(true)
Button_share_close:setCascadeOpacityEnabled(true)
Button_share_close:setPosition(487.6487, 390.4608)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_share_close)
layout:setPositionPercentX(0.8646)
layout:setPositionPercentY(0.8507)
layout:setPercentWidth(0.1472)
layout:setPercentHeight(0.1830)
layout:setSize({width = 83.0000, height = 84.0000})
layout:setLeftMargin(446.1487)
layout:setRightMargin(34.8513)
layout:setTopMargin(26.5392)
layout:setBottomMargin(348.4608)
share_bg:addChild(Button_share_close)

--Create Button_share_fb
local Button_share_fb = ccui.Button:create()
Button_share_fb:ignoreContentAdaptWithSize(false)
Button_share_fb:loadTextureNormal("res.2/share/share_facebook.png",0)
Button_share_fb:setTitleFontSize(14)
Button_share_fb:setTitleColor({r = 65, g = 65, b = 70})
Button_share_fb:setScale9Enabled(true)
Button_share_fb:setCapInsets({x = 15, y = 11, width = 90, height = 98})
Button_share_fb:setLayoutComponentEnabled(true)
Button_share_fb:setName("Button_share_fb")
Button_share_fb:setTag(78)
Button_share_fb:setCascadeColorEnabled(true)
Button_share_fb:setCascadeOpacityEnabled(true)
Button_share_fb:setPosition(140.0000, 230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_share_fb)
layout:setPositionPercentX(0.2482)
layout:setPositionPercentY(0.5011)
layout:setPercentWidth(0.2128)
layout:setPercentHeight(0.2614)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(80.0000)
layout:setRightMargin(364.0000)
layout:setTopMargin(169.0000)
layout:setBottomMargin(170.0000)
share_bg:addChild(Button_share_fb)

--Create Button_share_wx
local Button_share_wx = ccui.Button:create()
Button_share_wx:ignoreContentAdaptWithSize(false)
Button_share_wx:loadTextureNormal("res.2/share/share_wexin.png",0)
Button_share_wx:setTitleFontSize(14)
Button_share_wx:setTitleColor({r = 65, g = 65, b = 70})
Button_share_wx:setScale9Enabled(true)
Button_share_wx:setCapInsets({x = 15, y = 11, width = 90, height = 98})
Button_share_wx:setLayoutComponentEnabled(true)
Button_share_wx:setName("Button_share_wx")
Button_share_wx:setTag(80)
Button_share_wx:setCascadeColorEnabled(true)
Button_share_wx:setCascadeOpacityEnabled(true)
Button_share_wx:setPosition(290.0000, 230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_share_wx)
layout:setPositionPercentX(0.5142)
layout:setPositionPercentY(0.5011)
layout:setPercentWidth(0.2128)
layout:setPercentHeight(0.2614)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(230.0000)
layout:setRightMargin(214.0000)
layout:setTopMargin(169.0000)
layout:setBottomMargin(170.0000)
share_bg:addChild(Button_share_wx)

--Create Button_share_wb
local Button_share_wb = ccui.Button:create()
Button_share_wb:ignoreContentAdaptWithSize(false)
Button_share_wb:loadTextureNormal("res.2/share/share_weibo.png",0)
Button_share_wb:setTitleFontSize(14)
Button_share_wb:setTitleColor({r = 65, g = 65, b = 70})
Button_share_wb:setScale9Enabled(true)
Button_share_wb:setCapInsets({x = 15, y = 11, width = 90, height = 98})
Button_share_wb:setLayoutComponentEnabled(true)
Button_share_wb:setName("Button_share_wb")
Button_share_wb:setTag(81)
Button_share_wb:setCascadeColorEnabled(true)
Button_share_wb:setCascadeOpacityEnabled(true)
Button_share_wb:setPosition(440.0000, 230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_share_wb)
layout:setPositionPercentX(0.7801)
layout:setPositionPercentY(0.5011)
layout:setPercentWidth(0.2128)
layout:setPercentHeight(0.2614)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(380.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(169.0000)
layout:setBottomMargin(170.0000)
share_bg:addChild(Button_share_wb)

--Create General_line_4
local General_line_4 = cc.Sprite:create("res.2/General/General_line.png")
General_line_4:setName("General_line_4")
General_line_4:setTag(79)
General_line_4:setCascadeColorEnabled(true)
General_line_4:setCascadeOpacityEnabled(true)
General_line_4:setPosition(298.2300, 145.1363)
layout = ccui.LayoutComponent:bindLayoutComponent(General_line_4)
layout:setPositionPercentX(0.5288)
layout:setPositionPercentY(0.3162)
layout:setPercentWidth(0.8138)
layout:setPercentHeight(0.0131)
layout:setSize({width = 459.0000, height = 6.0000})
layout:setLeftMargin(68.7300)
layout:setRightMargin(36.2700)
layout:setTopMargin(310.8637)
layout:setBottomMargin(142.1363)
General_line_4:setBlendFunc({src = 1, dst = 771})
share_bg:addChild(General_line_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

