--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_item_bg
local Image_item_bg = ccui.ImageView:create()
Image_item_bg:ignoreContentAdaptWithSize(false)
Image_item_bg:loadTexture("res.2/SignLayer/sign_item_1.png",0)
Image_item_bg:setLayoutComponentEnabled(true)
Image_item_bg:setName("Image_item_bg")
Image_item_bg:setTag(268)
Image_item_bg:setCascadeColorEnabled(true)
Image_item_bg:setCascadeOpacityEnabled(true)
Image_item_bg:setPosition(73.0000, 67.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_item_bg)
layout:setSize({width = 146.0000, height = 134.0000})
layout:setRightMargin(-146.0000)
layout:setTopMargin(-134.0000)
Node:addChild(Image_item_bg)

--Create Image_item
local Image_item = ccui.ImageView:create()
Image_item:ignoreContentAdaptWithSize(false)
Image_item:loadTexture("res.2/SignLayer/sign_id1.png",0)
Image_item:setLayoutComponentEnabled(true)
Image_item:setName("Image_item")
Image_item:setTag(340)
Image_item:setCascadeColorEnabled(true)
Image_item:setCascadeOpacityEnabled(true)
Image_item:setPosition(77.7675, 77.1361)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_item)
layout:setSize({width = 100.0000, height = 81.0000})
layout:setLeftMargin(27.7675)
layout:setRightMargin(-127.7675)
layout:setTopMargin(-117.6361)
layout:setBottomMargin(36.6361)
Node:addChild(Image_item)

--Create num_text
local num_text = ccui.TextBMFont:create()
num_text:setFntFile("fnts/fnt.fnt")
num_text:setString([[10]])
num_text:setLayoutComponentEnabled(true)
num_text:setName("num_text")
num_text:setTag(281)
num_text:setCascadeColorEnabled(true)
num_text:setCascadeOpacityEnabled(true)
num_text:setPosition(70.0468, 20.2888)
num_text:setScaleX(0.9000)
num_text:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(num_text)
layout:setSize({width = 34.0000, height = 32.0000})
layout:setLeftMargin(53.0468)
layout:setRightMargin(-87.0468)
layout:setTopMargin(-36.2888)
layout:setBottomMargin(4.2888)
Node:addChild(num_text)

--Create sign_double
local sign_double = cc.Sprite:create("res.2/SignLayer/sign_double.png")
sign_double:setName("sign_double")
sign_double:setTag(304)
sign_double:setCascadeColorEnabled(true)
sign_double:setCascadeOpacityEnabled(true)
sign_double:setPosition(125.8343, 19.4902)
layout = ccui.LayoutComponent:bindLayoutComponent(sign_double)
layout:setSize({width = 76.0000, height = 78.0000})
layout:setLeftMargin(87.8343)
layout:setRightMargin(-163.8343)
layout:setTopMargin(-58.4902)
layout:setBottomMargin(-19.5098)
sign_double:setBlendFunc({src = 1, dst = 771})
Node:addChild(sign_double)

--Create sign_ok
local sign_ok = cc.Sprite:create("res.2/SignLayer/sign_ok.png")
sign_ok:setName("sign_ok")
sign_ok:setTag(270)
sign_ok:setCascadeColorEnabled(true)
sign_ok:setCascadeOpacityEnabled(true)
sign_ok:setPosition(20.7420, 2.6946)
layout = ccui.LayoutComponent:bindLayoutComponent(sign_ok)
layout:setSize({width = 67.0000, height = 56.0000})
layout:setLeftMargin(-12.7580)
layout:setRightMargin(-54.2420)
layout:setTopMargin(-30.6946)
layout:setBottomMargin(-25.3054)
sign_ok:setBlendFunc({src = 1, dst = 771})
Node:addChild(sign_ok)

--Create day_text
local day_text = ccui.TextBMFont:create()
day_text:setFntFile("fnts/fnt.fnt")
day_text:setString([[1天]])
day_text:setLayoutComponentEnabled(true)
day_text:setName("day_text")
day_text:setTag(292)
day_text:setCascadeColorEnabled(true)
day_text:setCascadeOpacityEnabled(true)
day_text:setPosition(25.4334, 113.7821)
day_text:setScaleX(0.5500)
day_text:setScaleY(0.5500)
day_text:setRotationSkewX(-45.0000)
day_text:setRotationSkewY(-45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(day_text)
layout:setSize({width = 48.0000, height = 32.0000})
layout:setLeftMargin(1.4334)
layout:setRightMargin(-49.4334)
layout:setTopMargin(-129.7821)
layout:setBottomMargin(97.7821)
Node:addChild(day_text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(20)
result['animation']:setTimeSpeed(0.5000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(125.8343)
localFrame:setY(19.4902)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(125.8343)
localFrame:setY(19.4902)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(125.8343)
localFrame:setY(19.4902)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(125.8343)
localFrame:setY(19.4902)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(125.8343)
localFrame:setY(19.4902)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(sign_double)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.1000)
localFrame:setScaleY(1.1000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(sign_double)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(sign_double)
--Create Animation List
local animation0 = {name="animation0", startIndex=0, endIndex=20}
result['animation']:addAnimationInfo(animation0)

result['root'] = Node
return result;
end

return Result

