local prefixFlag = "HALL_GAME_CONST_"
cc.exports.HALL_GAME_CONST = {
	SAVEDATA_HIGHLEVEL = "SAVEDATA_HIGHLEVEL",
	SAVEDATA_GOLDNUM = "SAVEDATA_GOLDNUM",	--金币
	SAVEDATA_MINTNUM = "SAVEDATA_MINTNUM",	--体力
	SAVEDATA_GEMNUM = "SAVEDATA_GEMNUM", --鱼干
	SAVEDATA_MAX_STAGE_STAR = "SAVEDATA_MAX_STAGE_STAR",			--保存最大关卡数对应的星球sid
	SAVEDATA_MAXSTATE = "SAVEDATA_MAXSTATE",					--保存最大关卡数
	SAVEDATA_MAXSTATE_ATK = "SAVEDATA_MAXSTATE_ATK",			--保存最大关卡数是否打过
	SAVEDATA_STATEINFO = "SAVEDATA_STATEINFO",
	SAVEDATA_ISFIRST = "SAVEDATA_ISFIRST",
	SAVEDATA_GAME_SIGNCHECK = "SAVEDATA_GAME_SIGNCHECK",
	SAVEDATA_CONFIGLEVEL_EDATA = "SAVEDATA_CONFIGLEVEL_EDATA",
	SAVEDATA_GAMEALLID = "SAVEDATA_GAMEALLID",
	SAVEDATA_SKILLCONFIG = "SAVEDATA_SKILLCONFIG",
	SAVEDATA_TASKAWARD = "SAVEDATA_TASKAWARD",
	SAVEDATA_GAME_ONLINE = "SAVEDATA_GAME_ONLINE",
	SAVEDATA_LOGINFACEBOOK = "SAVEDATA_LOGINFACEBOOK",

	SAVEDATA_GAMEGUIDEINDEX = "SAVEDATA_GAMEGUIDEINDEX",
	SAVEDATA_CURRENTLEVEL = "SAVEDATA_CURRENTLEVEL",
	SAVEDATA_CURRENTLEVEL_EXP = "SAVEDATA_CURRENTLEVEL_EXP",
	SAVEDATA_AUTOBUY_SKILL = "SAVEDATA_AUTOBUY_SKILL",  --自动购买技能

	SAVEDATA_LAST_LOGIN_DAY = "SAVEDATA_LAST_LOGIN_DAY",				--保存最后一次首登时间
	SAVEDATA_SIGN_NUM = "SAVEDATA_SIGN_NUM",						--保存签到天数
	SAVEDATA_SIGN_TIME = "SAVEDATA_SIGN_TIME",						--保存上次签到时间
	SAVEDATA_WEAPON_SID_LV = "SAVEDATA_WEAPON_SID_LV",			--保存已拥有的所有武器的sid和lv
	SAVEDATA_WEAR_WEAPON_SID = "SAVEDATA_WEAR_WEAPON_SID",			--保存穿戴中的所有武器的sid

	SAVEDATA_CAT_SKIN = "SAVEDATA_CAT_SKIN",				--保存已拥有的喵喵皮肤数据

	SAVEDATA_REGINER_BEGIN_TIME = "SAVEDATA_REGINER_BEGIN_TIME",				--保存体力恢复的开始时间
	SAVEDATA_REGINER_END_TIME = "SAVEDATA_REGINER_END_TIME",				--保存体力恢复的结束时间

	SAVEDATA_GAMESTORY = "SAVEDATA_GAMESTORY",    --保存是否播放了剧情动画

	SAVEDATA_REMOVE_AD = "SAVEDATA_REMOVE_AD",   --去除广告

	SAVEDATA_SOUND_ON = "SAVEDATA_SOUND_ON",  --声音是否开启
	SAVEDATA_MUSIC_ON = "SAVEDATA_MUSIC_ON" --音效是否开启	
}
