--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create back
local back = ccui.ImageView:create()
back:ignoreContentAdaptWithSize(false)
back:loadTexture("res/store/common_bg.png",0)
back:setScale9Enabled(true)
back:setCapInsets({x = 196, y = 260, width = 202, height = 268})
back:setLayoutComponentEnabled(true)
back:setName("back")
back:setTag(54)
back:setCascadeColorEnabled(true)
back:setCascadeOpacityEnabled(true)
back:setPosition(359.4828, 625.2179)
layout = ccui.LayoutComponent:bindLayoutComponent(back)
layout:setPositionPercentX(0.4993)
layout:setPositionPercentY(0.4885)
layout:setPercentWidth(0.8889)
layout:setPercentHeight(0.6172)
layout:setSize({width = 640.0000, height = 790.0000})
layout:setLeftMargin(39.4828)
layout:setRightMargin(40.5172)
layout:setTopMargin(259.7821)
layout:setBottomMargin(230.2179)
Layer:addChild(back)

--Create b_gb
local b_gb = ccui.Button:create()
b_gb:ignoreContentAdaptWithSize(false)
b_gb:loadTextureNormal("res/close.png",0)
b_gb:loadTexturePressed("res/closeclick.png",0)
b_gb:setTitleFontSize(14)
b_gb:setTitleColor({r = 65, g = 65, b = 70})
b_gb:setScale9Enabled(true)
b_gb:setCapInsets({x = 15, y = 11, width = 83, height = 97})
b_gb:setLayoutComponentEnabled(true)
b_gb:setName("b_gb")
b_gb:setTag(52)
b_gb:setCascadeColorEnabled(true)
b_gb:setCascadeOpacityEnabled(true)
b_gb:setPosition(625.7622, 980.0059)
layout = ccui.LayoutComponent:bindLayoutComponent(b_gb)
layout:setPositionPercentX(0.8691)
layout:setPositionPercentY(0.7656)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.0930)
layout:setSize({width = 113.0000, height = 119.0000})
layout:setLeftMargin(569.2622)
layout:setRightMargin(37.7378)
layout:setTopMargin(240.4941)
layout:setBottomMargin(920.5059)
Layer:addChild(b_gb)

--Create l_0
local l_0 = ccui.ListView:create()
l_0:setDirection(1)
l_0:setGravity(2)
l_0:ignoreContentAdaptWithSize(false)
l_0:setClippingEnabled(false)
l_0:setBackGroundColorType(1)
l_0:setBackGroundColor({r = 150, g = 150, b = 255})
l_0:setBackGroundColorOpacity(0)
l_0:setLayoutComponentEnabled(true)
l_0:setName("l_0")
l_0:setTag(237)
l_0:setCascadeColorEnabled(true)
l_0:setCascadeOpacityEnabled(true)
l_0:setPosition(115.9498, 332.1143)
layout = ccui.LayoutComponent:bindLayoutComponent(l_0)
layout:setPositionPercentX(0.1610)
layout:setPositionPercentY(0.2595)
layout:setPercentWidth(0.6722)
layout:setPercentHeight(0.4406)
layout:setSize({width = 484.0000, height = 564.0000})
layout:setLeftMargin(115.9498)
layout:setRightMargin(120.0502)
layout:setTopMargin(383.8857)
layout:setBottomMargin(332.1143)
Layer:addChild(l_0)

--Create achivementIcon_1
local achivementIcon_1 = cc.Sprite:create("res/achievement/achivementIcon.png")
achivementIcon_1:setName("achivementIcon_1")
achivementIcon_1:setTag(38)
achivementIcon_1:setCascadeColorEnabled(true)
achivementIcon_1:setCascadeOpacityEnabled(true)
achivementIcon_1:setPosition(360.0000, 953.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(achivementIcon_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7450)
layout:setSize({width = 106.0000, height = 57.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(235.5000)
layout:setRightMargin(235.5000)
layout:setTopMargin(280.4000)
layout:setBottomMargin(907.6000)
achivementIcon_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(achivementIcon_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

