--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("res/BeginScene/begin_bg.png",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(36)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Image_bg)

--Create Button_set
local Button_set = ccui.Button:create()
Button_set:ignoreContentAdaptWithSize(false)
Button_set:loadTextureNormal("res/BeginScene/set_bt.png",0)
Button_set:setTitleFontSize(14)
Button_set:setTitleColor({r = 65, g = 65, b = 70})
Button_set:setScale9Enabled(true)
Button_set:setCapInsets({x = 15, y = 11, width = 85, height = 85})
Button_set:setLayoutComponentEnabled(true)
Button_set:setName("Button_set")
Button_set:setTag(37)
Button_set:setCascadeColorEnabled(true)
Button_set:setCascadeOpacityEnabled(true)
Button_set:setPosition(614.6310, 153.6520)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_set)
layout:setPositionPercentX(0.8537)
layout:setPositionPercentY(0.1200)
layout:setPercentWidth(0.1597)
layout:setPercentHeight(0.0836)
layout:setSize({width = 115.0000, height = 107.0000})
layout:setLeftMargin(557.1310)
layout:setRightMargin(47.8690)
layout:setTopMargin(1072.8480)
layout:setBottomMargin(100.1520)
Layer:addChild(Button_set)

--Create Button_play
local Button_play = ccui.Button:create()
Button_play:ignoreContentAdaptWithSize(false)
Button_play:loadTextureNormal("res/BeginScene/begin_bt.png",0)
Button_play:setTitleFontSize(14)
Button_play:setTitleColor({r = 65, g = 65, b = 70})
Button_play:setScale9Enabled(true)
Button_play:setCapInsets({x = 15, y = 11, width = 285, height = 148})
Button_play:setLayoutComponentEnabled(true)
Button_play:setName("Button_play")
Button_play:setTag(38)
Button_play:setCascadeColorEnabled(true)
Button_play:setCascadeOpacityEnabled(true)
Button_play:setAnchorPoint(0.5320, 0.4769)
Button_play:setPosition(360.3081, 144.3316)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_play)
layout:setPositionPercentX(0.5004)
layout:setPositionPercentY(0.1128)
layout:setPercentWidth(0.4375)
layout:setPercentHeight(0.1328)
layout:setSize({width = 315.0000, height = 170.0000})
layout:setLeftMargin(192.7158)
layout:setRightMargin(212.2842)
layout:setTopMargin(1046.7350)
layout:setBottomMargin(63.2653)
Layer:addChild(Button_play)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(25)
result['animation']:setTimeSpeed(0.5000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(360.3081)
localFrame:setY(144.3316)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(360.3081)
localFrame:setY(144.3316)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(360.3081)
localFrame:setY(144.3316)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(360.3081)
localFrame:setY(144.3316)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(25)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(360.3081)
localFrame:setY(144.3316)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Button_play)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0500)
localFrame:setScaleY(1.0500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9500)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(25)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Button_play)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(25)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Button_play)
--Create Animation List
local animation0 = {name="animation0", startIndex=0, endIndex=25}
result['animation']:addAnimationInfo(animation0)

result['root'] = Layer
return result;
end

return Result

