--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create top_bg
local top_bg = ccui.ImageView:create()
top_bg:ignoreContentAdaptWithSize(false)
top_bg:loadTexture("res/GameMainScene/top_bg.png",0)
top_bg:setLayoutComponentEnabled(true)
top_bg:setName("top_bg")
top_bg:setTag(272)
top_bg:setCascadeColorEnabled(true)
top_bg:setCascadeOpacityEnabled(true)
top_bg:setPosition(360.0000, 1230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(top_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9609)
layout:setPercentWidth(0.9722)
layout:setPercentHeight(0.0562)
layout:setSize({width = 700.0000, height = 72.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(14.0000)
layout:setBottomMargin(1194.0000)
Layer:addChild(top_bg)

--Create top_shop2
local top_shop2 = ccui.ImageView:create()
top_shop2:ignoreContentAdaptWithSize(false)
top_shop2:loadTexture("res/GameMainScene/top_heart.png",0)
top_shop2:setScale9Enabled(true)
top_shop2:setCapInsets({x = 21, y = 18, width = 20, height = 19})
top_shop2:setTouchEnabled(true);
top_shop2:setLayoutComponentEnabled(true)
top_shop2:setName("top_shop2")
top_shop2:setTag(273)
top_shop2:setCascadeColorEnabled(true)
top_shop2:setCascadeOpacityEnabled(true)
top_shop2:setPosition(499.4298, 1232.0710)
top_shop2:setRotationSkewX(-12.6451)
top_shop2:setRotationSkewY(-12.6286)
layout = ccui.LayoutComponent:bindLayoutComponent(top_shop2)
layout:setPositionPercentX(0.6937)
layout:setPositionPercentY(0.9626)
layout:setPercentWidth(0.0861)
layout:setPercentHeight(0.0430)
layout:setSize({width = 62.0000, height = 55.0000})
layout:setLeftMargin(468.4298)
layout:setRightMargin(189.5702)
layout:setTopMargin(20.4292)
layout:setBottomMargin(1204.5710)
Layer:addChild(top_shop2)

--Create top_shop1
local top_shop1 = ccui.ImageView:create()
top_shop1:ignoreContentAdaptWithSize(false)
top_shop1:loadTexture("res/GameMainScene/top_fish.png",0)
top_shop1:setLayoutComponentEnabled(true)
top_shop1:setName("top_shop1")
top_shop1:setTag(274)
top_shop1:setCascadeColorEnabled(true)
top_shop1:setCascadeOpacityEnabled(true)
top_shop1:setPosition(270.1157, 1231.4890)
top_shop1:setScaleX(1.2700)
top_shop1:setScaleY(1.2700)
layout = ccui.LayoutComponent:bindLayoutComponent(top_shop1)
layout:setPositionPercentX(0.3752)
layout:setPositionPercentY(0.9621)
layout:setPercentWidth(0.0639)
layout:setPercentHeight(0.0305)
layout:setSize({width = 46.0000, height = 39.0000})
layout:setLeftMargin(247.1157)
layout:setRightMargin(426.8843)
layout:setTopMargin(29.0110)
layout:setBottomMargin(1211.9890)
Layer:addChild(top_shop1)

--Create top_shop0
local top_shop0 = ccui.ImageView:create()
top_shop0:ignoreContentAdaptWithSize(false)
top_shop0:loadTexture("res/GameMainScene/top_gold.png",0)
top_shop0:setLayoutComponentEnabled(true)
top_shop0:setName("top_shop0")
top_shop0:setTag(275)
top_shop0:setCascadeColorEnabled(true)
top_shop0:setCascadeOpacityEnabled(true)
top_shop0:setPosition(44.1426, 1232.6610)
top_shop0:setScaleX(1.2000)
top_shop0:setScaleY(1.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(top_shop0)
layout:setPositionPercentX(0.0613)
layout:setPositionPercentY(0.9630)
layout:setPercentWidth(0.0681)
layout:setPercentHeight(0.0383)
layout:setSize({width = 49.0000, height = 49.0000})
layout:setLeftMargin(19.6426)
layout:setRightMargin(651.3574)
layout:setTopMargin(22.8390)
layout:setBottomMargin(1208.1610)
Layer:addChild(top_shop0)

--Create gold_text
local gold_text = ccui.TextBMFont:create()
gold_text:setFntFile("fnts/fnt.fnt")
gold_text:setString([[0]])
gold_text:setLayoutComponentEnabled(true)
gold_text:setName("gold_text")
gold_text:setTag(276)
gold_text:setCascadeColorEnabled(true)
gold_text:setCascadeOpacityEnabled(true)
gold_text:setPosition(130.0000, 1232.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gold_text)
layout:setPositionPercentX(0.1806)
layout:setPositionPercentY(0.9625)
layout:setPercentWidth(0.3806)
layout:setPercentHeight(0.0250)
layout:setSize({width = 17.0000, height = 32.0000})
layout:setLeftMargin(117.5000)
layout:setRightMargin(577.5000)
layout:setTopMargin(32.0000)
layout:setBottomMargin(1216.0000)
Layer:addChild(gold_text)

--Create fish_text
local fish_text = ccui.TextBMFont:create()
fish_text:setFntFile("fnts/fnt.fnt")
fish_text:setString([[0]])
fish_text:setLayoutComponentEnabled(true)
fish_text:setName("fish_text")
fish_text:setTag(277)
fish_text:setCascadeColorEnabled(true)
fish_text:setCascadeOpacityEnabled(true)
fish_text:setPosition(360.0000, 1232.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fish_text)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9625)
layout:setPercentWidth(0.3806)
layout:setPercentHeight(0.0250)
layout:setSize({width = 17.0000, height = 32.0000})
layout:setLeftMargin(223.0000)
layout:setRightMargin(223.0000)
layout:setTopMargin(32.0000)
layout:setBottomMargin(1216.0000)
Layer:addChild(fish_text)

--Create giner_text
local giner_text = ccui.TextBMFont:create()
giner_text:setFntFile("fnts/fnt.fnt")
giner_text:setString([[0]])
giner_text:setLayoutComponentEnabled(true)
giner_text:setName("giner_text")
giner_text:setTag(278)
giner_text:setCascadeColorEnabled(true)
giner_text:setCascadeOpacityEnabled(true)
giner_text:setPosition(499.8560, 1236.3060)
giner_text:setScaleX(0.8000)
giner_text:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(giner_text)
layout:setPositionPercentX(0.6942)
layout:setPositionPercentY(0.9659)
layout:setPercentWidth(0.3806)
layout:setPercentHeight(0.0250)
layout:setSize({width = 17.0000, height = 32.0000})
layout:setLeftMargin(487.3560)
layout:setRightMargin(207.6440)
layout:setTopMargin(27.6943)
layout:setBottomMargin(1220.3060)
Layer:addChild(giner_text)

--Create shop_bt0
local shop_bt0 = ccui.Button:create()
shop_bt0:ignoreContentAdaptWithSize(false)
shop_bt0:loadTextureNormal("res/GameMainScene/shop_bt.png",0)
shop_bt0:loadTexturePressed("res/GameMainScene/shop_bt.png",0)
shop_bt0:setTitleFontSize(14)
shop_bt0:setTitleColor({r = 65, g = 65, b = 70})
shop_bt0:setScale9Enabled(true)
shop_bt0:setCapInsets({x = 8, y = 8, width = 34, height = 34})
shop_bt0:setLayoutComponentEnabled(true)
shop_bt0:setName("shop_bt0")
shop_bt0:setTag(279)
shop_bt0:setCascadeColorEnabled(true)
shop_bt0:setCascadeOpacityEnabled(true)
shop_bt0:setPosition(213.9576, 1232.7670)
layout = ccui.LayoutComponent:bindLayoutComponent(shop_bt0)
layout:setPositionPercentX(0.2972)
layout:setPositionPercentY(0.9631)
layout:setPercentWidth(0.0694)
layout:setPercentHeight(0.0391)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(188.9576)
layout:setRightMargin(481.0424)
layout:setTopMargin(22.2325)
layout:setBottomMargin(1207.7670)
Layer:addChild(shop_bt0)

--Create shop_bt1
local shop_bt1 = ccui.Button:create()
shop_bt1:ignoreContentAdaptWithSize(false)
shop_bt1:loadTextureNormal("res/GameMainScene/shop_bt.png",0)
shop_bt1:loadTexturePressed("res/GameMainScene/shop_bt.png",0)
shop_bt1:setTitleFontSize(14)
shop_bt1:setTitleColor({r = 65, g = 65, b = 70})
shop_bt1:setScale9Enabled(true)
shop_bt1:setCapInsets({x = 8, y = 8, width = 34, height = 34})
shop_bt1:setLayoutComponentEnabled(true)
shop_bt1:setName("shop_bt1")
shop_bt1:setTag(280)
shop_bt1:setCascadeColorEnabled(true)
shop_bt1:setCascadeOpacityEnabled(true)
shop_bt1:setPosition(439.8418, 1232.5070)
layout = ccui.LayoutComponent:bindLayoutComponent(shop_bt1)
layout:setPositionPercentX(0.6109)
layout:setPositionPercentY(0.9629)
layout:setPercentWidth(0.0694)
layout:setPercentHeight(0.0391)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(414.8418)
layout:setRightMargin(255.1582)
layout:setTopMargin(22.4927)
layout:setBottomMargin(1207.5070)
Layer:addChild(shop_bt1)

--Create shop_bt2
local shop_bt2 = ccui.Button:create()
shop_bt2:ignoreContentAdaptWithSize(false)
shop_bt2:loadTextureNormal("res/GameMainScene/shop_bt.png",0)
shop_bt2:loadTexturePressed("res/GameMainScene/shop_bt.png",0)
shop_bt2:setTitleFontSize(14)
shop_bt2:setTitleColor({r = 65, g = 65, b = 70})
shop_bt2:setScale9Enabled(true)
shop_bt2:setCapInsets({x = 8, y = 8, width = 34, height = 34})
shop_bt2:setLayoutComponentEnabled(true)
shop_bt2:setName("shop_bt2")
shop_bt2:setTag(281)
shop_bt2:setCascadeColorEnabled(true)
shop_bt2:setCascadeOpacityEnabled(true)
shop_bt2:setPosition(667.7740, 1233.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(shop_bt2)
layout:setPositionPercentX(0.9275)
layout:setPositionPercentY(0.9640)
layout:setPercentWidth(0.0694)
layout:setPercentHeight(0.0391)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(642.7740)
layout:setRightMargin(27.2260)
layout:setTopMargin(21.0996)
layout:setBottomMargin(1208.9000)
Layer:addChild(shop_bt2)

--Create reTime
local reTime = ccui.TextBMFont:create()
reTime:setFntFile("fnts/fnt.fnt")
reTime:setString([[FULL]])
reTime:setLayoutComponentEnabled(true)
reTime:setName("reTime")
reTime:setTag(282)
reTime:setCascadeColorEnabled(true)
reTime:setCascadeOpacityEnabled(true)
reTime:setPosition(594.3948, 1234.7160)
layout = ccui.LayoutComponent:bindLayoutComponent(reTime)
layout:setPositionPercentX(0.8255)
layout:setPositionPercentY(0.9646)
layout:setPercentWidth(0.3806)
layout:setPercentHeight(0.0250)
layout:setSize({width = 68.0000, height = 32.0000})
layout:setLeftMargin(545.3948)
layout:setRightMargin(76.6052)
layout:setTopMargin(29.2838)
layout:setBottomMargin(1218.7160)
Layer:addChild(reTime)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

