--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create light_1
local light_1 = cc.Sprite:create("res/RoleUpDialog/light.png")
light_1:setName("light_1")
light_1:setTag(18)
light_1:setCascadeColorEnabled(true)
light_1:setCascadeOpacityEnabled(true)
light_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(light_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize({width = 890.0000, height = 886.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(-85.0000)
layout:setRightMargin(-85.0000)
layout:setTopMargin(197.0000)
layout:setBottomMargin(197.0000)
light_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(light_1)

--Create dialogBack_1
local dialogBack_1 = cc.Sprite:create("res/RoleUpDialog/back.png")
dialogBack_1:setName("dialogBack_1")
dialogBack_1:setTag(127)
dialogBack_1:setCascadeColorEnabled(true)
dialogBack_1:setCascadeOpacityEnabled(true)
dialogBack_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(dialogBack_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6972)
layout:setPercentHeight(0.3492)
layout:setSize({width = 502.0000, height = 323.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(109.0000)
layout:setRightMargin(109.0000)
layout:setTopMargin(478.5000)
layout:setBottomMargin(478.5000)
dialogBack_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(dialogBack_1)

--Create loadingbar1_3
local loadingbar1_3 = cc.Sprite:create("res/RoleUpDialog/loadingbar1.png")
loadingbar1_3:setName("loadingbar1_3")
loadingbar1_3:setTag(259)
loadingbar1_3:setCascadeColorEnabled(true)
loadingbar1_3:setCascadeOpacityEnabled(true)
loadingbar1_3:setPosition(393.4990, 650.3647)
layout = ccui.LayoutComponent:bindLayoutComponent(loadingbar1_3)
layout:setPositionPercentX(0.5465)
layout:setPositionPercentY(0.5081)
layout:setSize({width = 315.0000, height = 30.0000})
layout:setLeftMargin(235.9990)
layout:setRightMargin(169.0010)
layout:setTopMargin(614.6353)
layout:setBottomMargin(635.3647)
loadingbar1_3:setBlendFunc({src = 770, dst = 771})
Layer:addChild(loadingbar1_3)

--Create lb_jy
local lb_jy = ccui.LoadingBar:create()
lb_jy:loadTexture("res/RoleUpDialog/loadingbar2.png",0)
lb_jy:ignoreContentAdaptWithSize(false)
lb_jy:setLayoutComponentEnabled(true)
lb_jy:setName("lb_jy")
lb_jy:setTag(129)
lb_jy:setCascadeColorEnabled(true)
lb_jy:setCascadeOpacityEnabled(true)
lb_jy:setPosition(393.1974, 650.1865)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_jy)
layout:setPositionPercentX(0.5461)
layout:setPositionPercentY(0.5080)
layout:setPercentWidth(0.4236)
layout:setPercentHeight(0.0156)
layout:setSize({width = 305.0000, height = 20.0000})
layout:setLeftMargin(240.6974)
layout:setRightMargin(174.3026)
layout:setTopMargin(619.8135)
layout:setBottomMargin(640.1865)
Layer:addChild(lb_jy)

--Create i_jtx_0
local i_jtx_0 = cc.Sprite:create("dialog/upRow.png")
i_jtx_0:setName("i_jtx_0")
i_jtx_0:setTag(500)
i_jtx_0:setCascadeColorEnabled(true)
i_jtx_0:setCascadeOpacityEnabled(true)
i_jtx_0:setPosition(334.0735, 685.5875)
i_jtx_0:setRotationSkewX(90.0000)
i_jtx_0:setRotationSkewY(90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(i_jtx_0)
layout:setPositionPercentX(0.4640)
layout:setPositionPercentY(0.5356)
layout:setSize({width = 31.0000, height = 25.0000})
layout:setLeftMargin(318.5735)
layout:setRightMargin(370.4265)
layout:setTopMargin(581.9125)
layout:setBottomMargin(673.0875)
i_jtx_0:setBlendFunc({src = 770, dst = 771})
Layer:addChild(i_jtx_0)

--Create i_jtx_1
local i_jtx_1 = cc.Sprite:create("dialog/upRow.png")
i_jtx_1:setName("i_jtx_1")
i_jtx_1:setTag(501)
i_jtx_1:setCascadeColorEnabled(true)
i_jtx_1:setCascadeOpacityEnabled(true)
i_jtx_1:setPosition(347.0152, 685.5875)
i_jtx_1:setRotationSkewX(90.0000)
i_jtx_1:setRotationSkewY(90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(i_jtx_1)
layout:setPositionPercentX(0.4820)
layout:setPositionPercentY(0.5356)
layout:setSize({width = 31.0000, height = 25.0000})
layout:setLeftMargin(331.5152)
layout:setRightMargin(357.4848)
layout:setTopMargin(581.9125)
layout:setBottomMargin(673.0875)
i_jtx_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(i_jtx_1)

--Create i_jtx_2
local i_jtx_2 = cc.Sprite:create("dialog/upRow.png")
i_jtx_2:setName("i_jtx_2")
i_jtx_2:setTag(502)
i_jtx_2:setCascadeColorEnabled(true)
i_jtx_2:setCascadeOpacityEnabled(true)
i_jtx_2:setPosition(359.9572, 685.5875)
i_jtx_2:setRotationSkewX(90.0000)
i_jtx_2:setRotationSkewY(90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(i_jtx_2)
layout:setPositionPercentX(0.4999)
layout:setPositionPercentY(0.5356)
layout:setSize({width = 31.0000, height = 25.0000})
layout:setLeftMargin(344.4572)
layout:setRightMargin(344.5428)
layout:setTopMargin(581.9125)
layout:setBottomMargin(673.0875)
i_jtx_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(i_jtx_2)

--Create bf_ms
local bf_ms = ccui.TextBMFont:create()
bf_ms:setFntFile("fnts/fnt.fnt")
bf_ms:setString([[铲屎官，你已经升级到XX级了!!]])
bf_ms:setLayoutComponentEnabled(true)
bf_ms:setName("bf_ms")
bf_ms:setTag(161)
bf_ms:setCascadeColorEnabled(true)
bf_ms:setCascadeOpacityEnabled(true)
bf_ms:setAnchorPoint(0.0000, 0.5000)
bf_ms:setPosition(182.0160, 590.3170)
bf_ms:setScaleX(0.8000)
bf_ms:setScaleY(0.8000)
bf_ms:setColor({r = 221, g = 201, b = 147})
layout = ccui.LayoutComponent:bindLayoutComponent(bf_ms)
layout:setPositionPercentX(0.2528)
layout:setPositionPercentY(0.4612)
layout:setPercentWidth(0.6444)
layout:setPercentHeight(0.0250)
layout:setSize({width = 464.0000, height = 32.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(182.0160)
layout:setRightMargin(73.9840)
layout:setTopMargin(673.6830)
layout:setBottomMargin(574.3170)
Layer:addChild(bf_ms)

--Create bf_jy
local bf_jy = ccui.TextBMFont:create()
bf_jy:setFntFile("fnts/fnt.fnt")
bf_jy:setString([[12345]])
bf_jy:setLayoutComponentEnabled(true)
bf_jy:setName("bf_jy")
bf_jy:setTag(163)
bf_jy:setCascadeColorEnabled(true)
bf_jy:setCascadeOpacityEnabled(true)
bf_jy:setAnchorPoint(0.0000, 0.5000)
bf_jy:setPosition(374.2885, 686.4640)
bf_jy:setScaleX(0.9000)
bf_jy:setScaleY(0.9000)
bf_jy:setColor({r = 221, g = 201, b = 147})
layout = ccui.LayoutComponent:bindLayoutComponent(bf_jy)
layout:setPositionPercentX(0.5198)
layout:setPositionPercentY(0.5363)
layout:setPercentWidth(0.1181)
layout:setPercentHeight(0.0250)
layout:setSize({width = 85.0000, height = 32.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(374.2885)
layout:setRightMargin(260.7115)
layout:setTopMargin(577.5360)
layout:setBottomMargin(670.4640)
Layer:addChild(bf_jy)

--Create LV_1
local LV_1 = cc.Sprite:create("res/RoleUpDialog/LV.png")
LV_1:setName("LV_1")
LV_1:setTag(257)
LV_1:setCascadeColorEnabled(true)
LV_1:setCascadeOpacityEnabled(true)
LV_1:setPosition(199.0642, 704.8589)
layout = ccui.LayoutComponent:bindLayoutComponent(LV_1)
layout:setPositionPercentX(0.2765)
layout:setPositionPercentY(0.5507)
layout:setSize({width = 52.0000, height = 32.0000})
layout:setLeftMargin(173.0642)
layout:setRightMargin(494.9358)
layout:setTopMargin(559.1411)
layout:setBottomMargin(688.8589)
LV_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(LV_1)

--Create EXP_2
local EXP_2 = cc.Sprite:create("res/RoleUpDialog/EXP.png")
EXP_2:setName("EXP_2")
EXP_2:setTag(258)
EXP_2:setCascadeColorEnabled(true)
EXP_2:setCascadeOpacityEnabled(true)
EXP_2:setPosition(202.0637, 649.8646)
layout = ccui.LayoutComponent:bindLayoutComponent(EXP_2)
layout:setPositionPercentX(0.2806)
layout:setPositionPercentY(0.5077)
layout:setSize({width = 61.0000, height = 35.0000})
layout:setLeftMargin(171.5637)
layout:setRightMargin(487.4363)
layout:setTopMargin(612.6354)
layout:setBottomMargin(632.3646)
EXP_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(EXP_2)

--Create bf_dj
local bf_dj = ccui.TextAtlas:create([[23]],
													"res/RoleUpDialog/number.png",
													24,
													32,
													".")
bf_dj:setLayoutComponentEnabled(true)
bf_dj:setName("bf_dj")
bf_dj:setTag(260)
bf_dj:setCascadeColorEnabled(true)
bf_dj:setCascadeOpacityEnabled(true)
bf_dj:setAnchorPoint(0.0000, 0.5000)
bf_dj:setPosition(233.7735, 705.8589)
layout = ccui.LayoutComponent:bindLayoutComponent(bf_dj)
layout:setPositionPercentX(0.3247)
layout:setPositionPercentY(0.5515)
layout:setPercentWidth(0.2333)
layout:setPercentHeight(0.0141)
layout:setSize({width = 48.0000, height = 32.0000})
layout:setLeftMargin(233.7735)
layout:setRightMargin(438.2265)
layout:setTopMargin(558.1411)
layout:setBottomMargin(689.8589)
Layer:addChild(bf_dj)

--Create levelup_4
local levelup_4 = cc.Sprite:create("res/RoleUpDialog/levelup.png")
levelup_4:setName("levelup_4")
levelup_4:setTag(261)
levelup_4:setCascadeColorEnabled(true)
levelup_4:setCascadeOpacityEnabled(true)
levelup_4:setPosition(360.0000, 850.3220)
layout = ccui.LayoutComponent:bindLayoutComponent(levelup_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6643)
layout:setSize({width = 333.0000, height = 97.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(193.5000)
layout:setRightMargin(193.5000)
layout:setTopMargin(381.1780)
layout:setBottomMargin(801.8220)
levelup_4:setBlendFunc({src = 770, dst = 771})
Layer:addChild(levelup_4)

--Create caticon_5
local caticon_5 = cc.Sprite:create("res/GameMainScene/caticon.png")
caticon_5:setName("caticon_5")
caticon_5:setTag(262)
caticon_5:setCascadeColorEnabled(true)
caticon_5:setCascadeOpacityEnabled(true)
caticon_5:setPosition(518.2158, 692.0073)
caticon_5:setScaleX(-0.6000)
caticon_5:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(caticon_5)
layout:setPositionPercentX(0.7197)
layout:setPositionPercentY(0.5406)
layout:setSize({width = 109.0000, height = 126.0000})
layout:setLeftMargin(463.7158)
layout:setRightMargin(147.2842)
layout:setTopMargin(524.9927)
layout:setBottomMargin(629.0073)
caticon_5:setBlendFunc({src = 770, dst = 771})
Layer:addChild(caticon_5)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(360)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(360.0000)
localFrame:setY(640.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(360)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(350.0844)
localFrame:setY(677.3307)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(light_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(360)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(light_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(360)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(360.0000)
localFrame:setSkewY(360.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(light_1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

