--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("res/paylayer/background.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(226)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6931)
layout:setPercentHeight(0.3461)
layout:setSize({width = 499.0000, height = 443.0000})
layout:setLeftMargin(110.5000)
layout:setRightMargin(110.5000)
layout:setTopMargin(418.5000)
layout:setBottomMargin(418.5000)
Layer:addChild(Image_1)

--Create gopay
local gopay = ccui.Button:create()
gopay:ignoreContentAdaptWithSize(false)
gopay:loadTextureNormal("res/paylayer/buy.png",0)
gopay:setTitleFontSize(14)
gopay:setTitleColor({r = 65, g = 65, b = 70})
gopay:setScale9Enabled(true)
gopay:setCapInsets({x = 15, y = 11, width = 142, height = 48})
gopay:setLayoutComponentEnabled(true)
gopay:setName("gopay")
gopay:setTag(227)
gopay:setCascadeColorEnabled(true)
gopay:setCascadeOpacityEnabled(true)
gopay:setPosition(368.0000, 519.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gopay)
layout:setPositionPercentX(0.5111)
layout:setPositionPercentY(0.4055)
layout:setPercentWidth(0.2389)
layout:setPercentHeight(0.0547)
layout:setSize({width = 172.0000, height = 70.0000})
layout:setLeftMargin(282.0000)
layout:setRightMargin(266.0000)
layout:setTopMargin(726.0000)
layout:setBottomMargin(484.0000)
Layer:addChild(gopay)

--Create closebtn
local closebtn = ccui.Button:create()
closebtn:ignoreContentAdaptWithSize(false)
closebtn:loadTextureNormal("res/close.png",0)
closebtn:setTitleFontSize(14)
closebtn:setTitleColor({r = 65, g = 65, b = 70})
closebtn:setScale9Enabled(true)
closebtn:setCapInsets({x = 15, y = 11, width = 83, height = 97})
closebtn:setLayoutComponentEnabled(true)
closebtn:setName("closebtn")
closebtn:setTag(228)
closebtn:setCascadeColorEnabled(true)
closebtn:setCascadeOpacityEnabled(true)
closebtn:setPosition(560.0000, 807.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(closebtn)
layout:setPositionPercentX(0.7778)
layout:setPositionPercentY(0.6305)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.0930)
layout:setSize({width = 113.0000, height = 119.0000})
layout:setLeftMargin(503.5000)
layout:setRightMargin(103.5000)
layout:setTopMargin(413.5000)
layout:setBottomMargin(747.5000)
Layer:addChild(closebtn)

--Create text
local text = ccui.TextBMFont:create()
text:setFntFile("fnts/fnt.fnt")
text:setString([[花费10元]])
text:setLayoutComponentEnabled(true)
text:setName("text")
text:setTag(229)
text:setCascadeColorEnabled(true)
text:setCascadeOpacityEnabled(true)
text:setPosition(364.0000, 583.0000)
text:setScaleX(0.9000)
text:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(text)
layout:setPositionPercentX(0.5056)
layout:setPositionPercentY(0.4555)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0250)
layout:setSize({width = 133.0000, height = 32.0000})
layout:setLeftMargin(297.5000)
layout:setRightMargin(289.5000)
layout:setTopMargin(681.0000)
layout:setBottomMargin(567.0000)
Layer:addChild(text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

