--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create back_bg
local back_bg = ccui.ImageView:create()
back_bg:ignoreContentAdaptWithSize(false)
back_bg:loadTexture("res/setingLayer/background.png",0)
back_bg:setScale9Enabled(true)
back_bg:setCapInsets({x = 15, y = 15, width = 564, height = 612})
back_bg:setTouchEnabled(true);
back_bg:setLayoutComponentEnabled(true)
back_bg:setName("back_bg")
back_bg:setTag(53)
back_bg:setCascadeColorEnabled(true)
back_bg:setCascadeOpacityEnabled(true)
back_bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8250)
layout:setPercentHeight(0.5016)
layout:setSize({width = 594.0000, height = 642.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(63.0000)
layout:setRightMargin(63.0000)
layout:setTopMargin(319.0000)
layout:setBottomMargin(319.0000)
Scene:addChild(back_bg)

--Create sound_bt
local sound_bt = ccui.Button:create()
sound_bt:ignoreContentAdaptWithSize(false)
sound_bt:loadTextureNormal("res/setingLayer/sound.png",0)
sound_bt:setTitleFontSize(14)
sound_bt:setTitleColor({r = 65, g = 65, b = 70})
sound_bt:setScale9Enabled(true)
sound_bt:setCapInsets({x = 15, y = 11, width = 90, height = 89})
sound_bt:setLayoutComponentEnabled(true)
sound_bt:setName("sound_bt")
sound_bt:setTag(54)
sound_bt:setCascadeColorEnabled(true)
sound_bt:setCascadeOpacityEnabled(true)
sound_bt:setPosition(250.0000, 780.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sound_bt)
layout:setPositionPercentX(0.3472)
layout:setPositionPercentY(0.6094)
layout:setPercentWidth(0.1667)
layout:setPercentHeight(0.0867)
layout:setSize({width = 120.0000, height = 111.0000})
layout:setLeftMargin(190.0000)
layout:setRightMargin(410.0000)
layout:setTopMargin(444.5000)
layout:setBottomMargin(724.5000)
Scene:addChild(sound_bt)

--Create music_bt
local music_bt = ccui.Button:create()
music_bt:ignoreContentAdaptWithSize(false)
music_bt:loadTextureNormal("res/setingLayer/music.png",0)
music_bt:setTitleFontSize(14)
music_bt:setTitleColor({r = 65, g = 65, b = 70})
music_bt:setScale9Enabled(true)
music_bt:setCapInsets({x = 15, y = 11, width = 90, height = 89})
music_bt:setLayoutComponentEnabled(true)
music_bt:setName("music_bt")
music_bt:setTag(55)
music_bt:setCascadeColorEnabled(true)
music_bt:setCascadeOpacityEnabled(true)
music_bt:setPosition(470.0000, 780.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(music_bt)
layout:setPositionPercentX(0.6528)
layout:setPositionPercentY(0.6094)
layout:setPercentWidth(0.1667)
layout:setPercentHeight(0.0867)
layout:setSize({width = 120.0000, height = 111.0000})
layout:setLeftMargin(410.0000)
layout:setRightMargin(190.0000)
layout:setTopMargin(444.5000)
layout:setBottomMargin(724.5000)
Scene:addChild(music_bt)

--Create Button_3
local Button_3 = ccui.Button:create()
Button_3:ignoreContentAdaptWithSize(false)
Button_3:loadTextureNormal("res/close.png",0)
Button_3:setTitleFontSize(14)
Button_3:setTitleColor({r = 65, g = 65, b = 70})
Button_3:setScale9Enabled(true)
Button_3:setCapInsets({x = 15, y = 11, width = 83, height = 97})
Button_3:setLayoutComponentEnabled(true)
Button_3:setName("Button_3")
Button_3:setTag(56)
Button_3:setCascadeColorEnabled(true)
Button_3:setCascadeOpacityEnabled(true)
Button_3:setPosition(610.0897, 924.7441)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3)
layout:setPositionPercentX(0.8473)
layout:setPositionPercentY(0.7225)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.0930)
layout:setSize({width = 113.0000, height = 119.0000})
layout:setLeftMargin(553.5897)
layout:setRightMargin(53.4103)
layout:setTopMargin(295.7559)
layout:setBottomMargin(865.2441)
Scene:addChild(Button_3)

--Create setting_1
local setting_1 = cc.Sprite:create("res/setingLayer/setting.png")
setting_1:setName("setting_1")
setting_1:setTag(147)
setting_1:setCascadeColorEnabled(true)
setting_1:setCascadeOpacityEnabled(true)
setting_1:setPosition(360.0000, 892.1017)
layout = ccui.LayoutComponent:bindLayoutComponent(setting_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6970)
layout:setPercentWidth(0.3056)
layout:setPercentHeight(0.0469)
layout:setSize({width = 220.0000, height = 60.0000})
layout:setLeftMargin(250.0000)
layout:setRightMargin(250.0000)
layout:setTopMargin(357.8983)
layout:setBottomMargin(862.1017)
setting_1:setBlendFunc({src = 770, dst = 771})
Scene:addChild(setting_1)

--Create b_rate
local b_rate = ccui.Button:create()
b_rate:ignoreContentAdaptWithSize(false)
b_rate:loadTextureNormal("res/setingLayer/rate.png",0)
b_rate:setTitleFontSize(14)
b_rate:setTitleColor({r = 65, g = 65, b = 70})
b_rate:setScale9Enabled(true)
b_rate:setCapInsets({x = 15, y = 11, width = 114, height = 29})
b_rate:setLayoutComponentEnabled(true)
b_rate:setName("b_rate")
b_rate:setTag(148)
b_rate:setCascadeColorEnabled(true)
b_rate:setCascadeOpacityEnabled(true)
b_rate:setPosition(360.0000, 422.0088)
layout = ccui.LayoutComponent:bindLayoutComponent(b_rate)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3297)
layout:setPercentWidth(0.2000)
layout:setPercentHeight(0.0398)
layout:setSize({width = 144.0000, height = 51.0000})
layout:setLeftMargin(288.0000)
layout:setRightMargin(288.0000)
layout:setTopMargin(832.4912)
layout:setBottomMargin(396.5088)
Scene:addChild(b_rate)

--Create BitmapFontLabel_1
local BitmapFontLabel_1 = ccui.TextBMFont:create()
BitmapFontLabel_1:setFntFile("fnts/fnt.fnt")
BitmapFontLabel_1:setString([[Give Me Five Score if You Like This Game!]])
BitmapFontLabel_1:setLayoutComponentEnabled(true)
BitmapFontLabel_1:setName("BitmapFontLabel_1")
BitmapFontLabel_1:setTag(15)
BitmapFontLabel_1:setCascadeColorEnabled(true)
BitmapFontLabel_1:setCascadeOpacityEnabled(true)
BitmapFontLabel_1:setPosition(360.0000, 380.0000)
BitmapFontLabel_1:setScaleX(0.5000)
BitmapFontLabel_1:setScaleY(0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2969)
layout:setPercentWidth(0.9639)
layout:setPercentHeight(0.0250)
layout:setSize({width = 694.0000, height = 32.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(884.0000)
layout:setBottomMargin(364.0000)
Scene:addChild(BitmapFontLabel_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

