--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 154.0000, height = 154.0000})

--Create can_sign
local can_sign = ccui.ImageView:create()
can_sign:ignoreContentAdaptWithSize(false)
can_sign:loadTexture("res/SignLayer/can_sign.png",0)
can_sign:setLayoutComponentEnabled(true)
can_sign:setName("can_sign")
can_sign:setTag(175)
can_sign:setCascadeColorEnabled(true)
can_sign:setCascadeOpacityEnabled(true)
can_sign:setPosition(77.0000, 77.0000)
can_sign:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(can_sign)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4933)
layout:setPercentHeight(0.4873)
layout:setSize({width = 74.0000, height = 77.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(40.0000)
layout:setTopMargin(38.5000)
layout:setBottomMargin(38.5000)
Layer:addChild(can_sign)

--Create back_bg
local back_bg = ccui.ImageView:create()
back_bg:ignoreContentAdaptWithSize(false)
back_bg:loadTexture("res/SignLayer/blank.png",0)
back_bg:setScale9Enabled(true)
back_bg:setCapInsets({x = 15, y = 15, width = 120, height = 128})
back_bg:setTouchEnabled(true);
back_bg:setLayoutComponentEnabled(true)
back_bg:setName("back_bg")
back_bg:setTag(94)
back_bg:setCascadeColorEnabled(true)
back_bg:setCascadeOpacityEnabled(true)
back_bg:setPosition(77.0000, 77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0267)
layout:setPercentHeight(0.9747)
layout:setSize({width = 154.0000, height = 154.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(-2.0000)
layout:setRightMargin(-2.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(2.0000)
Layer:addChild(back_bg)

--Create color
local color = ccui.ImageView:create()
color:ignoreContentAdaptWithSize(false)
color:loadTexture("res/SignLayer/already.png",0)
color:setLayoutComponentEnabled(true)
color:setName("color")
color:setTag(74)
color:setCascadeColorEnabled(true)
color:setCascadeOpacityEnabled(true)
color:setPosition(75.0000, 79.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(color)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0267)
layout:setPercentHeight(0.9747)
layout:setSize({width = 154.0000, height = 154.0000})
layout:setLeftMargin(-2.0000)
layout:setRightMargin(-2.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(2.0000)
Layer:addChild(color)

--Create day_text
local day_text = ccui.TextBMFont:create()
day_text:setFntFile("fnts/fnt.fnt")
day_text:setString([[第一天]])
day_text:setLayoutComponentEnabled(true)
day_text:setName("day_text")
day_text:setTag(125)
day_text:setCascadeColorEnabled(true)
day_text:setCascadeOpacityEnabled(true)
day_text:setPosition(27.5969, 130.8667)
day_text:setScaleX(0.5500)
day_text:setScaleY(0.5500)
day_text:setRotationSkewX(-44.9990)
day_text:setRotationSkewY(-45.0055)
layout = ccui.LayoutComponent:bindLayoutComponent(day_text)
layout:setPositionPercentX(0.1840)
layout:setPositionPercentY(0.8283)
layout:setPercentWidth(1.8267)
layout:setPercentHeight(0.2025)
layout:setSize({width = 99.0000, height = 32.0000})
layout:setLeftMargin(-21.9031)
layout:setRightMargin(72.9031)
layout:setTopMargin(11.1333)
layout:setBottomMargin(114.8667)
Layer:addChild(day_text)

--Create light
local light = ccui.ImageView:create()
light:ignoreContentAdaptWithSize(false)
light:loadTexture("res/SignLayer/doubledaylights.png",0)
light:setScale9Enabled(true)
light:setCapInsets({x = 63, y = 52, width = 66, height = 56})
light:setLayoutComponentEnabled(true)
light:setName("light")
light:setTag(95)
light:setCascadeColorEnabled(true)
light:setCascadeOpacityEnabled(true)
light:setPosition(77.0000, 77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(light)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.2800)
layout:setPercentHeight(1.0127)
layout:setSize({width = 192.0000, height = 160.0000})
layout:setLeftMargin(-19.0000)
layout:setRightMargin(-19.0000)
layout:setTopMargin(-3.0000)
layout:setBottomMargin(-3.0000)
Layer:addChild(light)

--Create reward_image
local reward_image = cc.Sprite:create("res/SignLayer/coin_0.png")
reward_image:setName("reward_image")
reward_image:setTag(396)
reward_image:setCascadeColorEnabled(true)
reward_image:setCascadeOpacityEnabled(true)
reward_image:setPosition(77.0000, 93.9400)
layout = ccui.LayoutComponent:bindLayoutComponent(reward_image)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6100)
layout:setSize({width = 87.0000, height = 71.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(37.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(23.1200)
layout:setBottomMargin(57.8800)
reward_image:setBlendFunc({src = 770, dst = 771})
Layer:addChild(reward_image)

--Create double
local double = ccui.ImageView:create()
double:ignoreContentAdaptWithSize(false)
double:loadTexture("res/SignLayer/doubleday.png",0)
double:setLayoutComponentEnabled(true)
double:setName("double")
double:setTag(96)
double:setCascadeColorEnabled(true)
double:setCascadeOpacityEnabled(true)
double:setPosition(77.0000, 56.9646)
layout = ccui.LayoutComponent:bindLayoutComponent(double)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3699)
layout:setPercentWidth(0.6558)
layout:setPercentHeight(0.2208)
layout:setSize({width = 101.0000, height = 34.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(26.5000)
layout:setRightMargin(26.5000)
layout:setTopMargin(80.0354)
layout:setBottomMargin(39.9646)
Layer:addChild(double)

--Create num_text
local num_text = ccui.TextBMFont:create()
num_text:setFntFile("fnts/fnt.fnt")
num_text:setString([[500]])
num_text:setLayoutComponentEnabled(true)
num_text:setName("num_text")
num_text:setTag(128)
num_text:setCascadeColorEnabled(true)
num_text:setCascadeOpacityEnabled(true)
num_text:setPosition(77.0000, 21.5600)
num_text:setScaleX(0.9000)
num_text:setScaleY(0.9000)
num_text:setColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(num_text)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1400)
layout:setPercentWidth(1.8267)
layout:setPercentHeight(0.2025)
layout:setSize({width = 51.0000, height = 32.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(51.5000)
layout:setRightMargin(51.5000)
layout:setTopMargin(116.4400)
layout:setBottomMargin(5.5600)
Layer:addChild(num_text)

--Create sure_image
local sure_image = ccui.ImageView:create()
sure_image:ignoreContentAdaptWithSize(false)
sure_image:loadTexture("res/SignLayer/sure_sign.png",0)
sure_image:setScale9Enabled(true)
sure_image:setCapInsets({x = 42, y = 18, width = 45, height = 20})
sure_image:setLayoutComponentEnabled(true)
sure_image:setName("sure_image")
sure_image:setTag(93)
sure_image:setCascadeColorEnabled(true)
sure_image:setCascadeOpacityEnabled(true)
sure_image:setPosition(77.0000, 77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sure_image)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8600)
layout:setPercentHeight(0.3544)
layout:setSize({width = 129.0000, height = 56.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(10.5000)
layout:setRightMargin(10.5000)
layout:setTopMargin(51.0000)
layout:setBottomMargin(51.0000)
Layer:addChild(sure_image)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

