--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create back_bg
local back_bg = ccui.ImageView:create()
back_bg:ignoreContentAdaptWithSize(false)
back_bg:loadTexture("res/SignLayer/background.png",0)
back_bg:setLayoutComponentEnabled(true)
back_bg:setName("back_bg")
back_bg:setTag(115)
back_bg:setCascadeColorEnabled(true)
back_bg:setCascadeOpacityEnabled(true)
back_bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.7813)
layout:setSize({width = 720.0000, height = 1000.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setTopMargin(140.0000)
layout:setBottomMargin(140.0000)
Layer:addChild(back_bg)

--Create close_bt
local close_bt = ccui.Button:create()
close_bt:ignoreContentAdaptWithSize(false)
close_bt:loadTextureNormal("res/close.png",0)
close_bt:setTitleFontSize(14)
close_bt:setTitleColor({r = 65, g = 65, b = 70})
close_bt:setScale9Enabled(true)
close_bt:setCapInsets({x = 15, y = 11, width = 83, height = 97})
close_bt:setLayoutComponentEnabled(true)
close_bt:setName("close_bt")
close_bt:setTag(116)
close_bt:setCascadeColorEnabled(true)
close_bt:setCascadeOpacityEnabled(true)
close_bt:setPosition(641.7780, 1052.2980)
layout = ccui.LayoutComponent:bindLayoutComponent(close_bt)
layout:setPositionPercentX(0.8914)
layout:setPositionPercentY(0.8221)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.0930)
layout:setSize({width = 113.0000, height = 119.0000})
layout:setLeftMargin(585.2780)
layout:setRightMargin(21.7220)
layout:setTopMargin(168.2018)
layout:setBottomMargin(992.7982)
Layer:addChild(close_bt)

--Create sign_bt
local sign_bt = ccui.Button:create()
sign_bt:ignoreContentAdaptWithSize(false)
sign_bt:loadTextureNormal("res/SignLayer/signin.png",0)
sign_bt:setTitleFontSize(14)
sign_bt:setTitleColor({r = 65, g = 65, b = 70})
sign_bt:setScale9Enabled(true)
sign_bt:setCapInsets({x = 15, y = 11, width = 240, height = 71})
sign_bt:setLayoutComponentEnabled(true)
sign_bt:setName("sign_bt")
sign_bt:setTag(117)
sign_bt:setCascadeColorEnabled(true)
sign_bt:setCascadeOpacityEnabled(true)
sign_bt:setPosition(360.1104, 326.5574)
layout = ccui.LayoutComponent:bindLayoutComponent(sign_bt)
layout:setPositionPercentX(0.5002)
layout:setPositionPercentY(0.2551)
layout:setPercentWidth(0.3750)
layout:setPercentHeight(0.0727)
layout:setSize({width = 270.0000, height = 93.0000})
layout:setLeftMargin(225.1104)
layout:setRightMargin(224.8896)
layout:setTopMargin(906.9426)
layout:setBottomMargin(280.0574)
Layer:addChild(sign_bt)

--Create top_tip
local top_tip = cc.Sprite:create("res/SignLayer/title.png")
top_tip:setName("top_tip")
top_tip:setTag(147)
top_tip:setCascadeColorEnabled(true)
top_tip:setCascadeOpacityEnabled(true)
top_tip:setPosition(360.0000, 1040.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(top_tip)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8125)
layout:setSize({width = 374.0000, height = 59.0000})
layout:setLeftMargin(239.0000)
layout:setRightMargin(239.0000)
layout:setTopMargin(206.5000)
layout:setBottomMargin(1006.5000)
top_tip:setBlendFunc({src = 770, dst = 771})
Layer:addChild(top_tip)

--Create item_scr
local item_scr = ccui.ScrollView:create()
item_scr:setBounceEnabled(true)
item_scr:setInnerContainerSize({width = 505, height = 583})
item_scr:ignoreContentAdaptWithSize(false)
item_scr:setClippingEnabled(true)
item_scr:setBackGroundColorOpacity(102)
item_scr:setLayoutComponentEnabled(true)
item_scr:setName("item_scr")
item_scr:setTag(119)
item_scr:setCascadeColorEnabled(true)
item_scr:setCascadeOpacityEnabled(true)
item_scr:setPosition(105.1848, 396.4587)
layout = ccui.LayoutComponent:bindLayoutComponent(item_scr)
layout:setPositionPercentX(0.1461)
layout:setPositionPercentY(0.3097)
layout:setPercentWidth(0.7014)
layout:setPercentHeight(0.4555)
layout:setSize({width = 505.0000, height = 583.0000})
layout:setLeftMargin(105.1848)
layout:setRightMargin(109.8152)
layout:setTopMargin(300.5413)
layout:setBottomMargin(396.4587)
Layer:addChild(item_scr)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

