--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(33)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setOpacity(186)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Panel_1)

--Create bg_1
local bg_1 = cc.Sprite:create("res/waitDialog/bg.png")
bg_1:setName("bg_1")
bg_1:setTag(25)
bg_1:setCascadeColorEnabled(true)
bg_1:setCascadeOpacityEnabled(true)
bg_1:setPosition(363.3840, 768.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_1)
layout:setPositionPercentX(0.5047)
layout:setPositionPercentY(0.6000)
layout:setSize({width = 502.0000, height = 447.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(112.3536)
layout:setRightMargin(105.6464)
layout:setTopMargin(288.5002)
layout:setBottomMargin(544.4998)
bg_1:setBlendFunc({src = 770, dst = 771})
Layer:addChild(bg_1)

--Create b_1
local b_1 = ccui.Button:create()
b_1:ignoreContentAdaptWithSize(false)
b_1:loadTextureNormal("res/close.png",0)
b_1:loadTexturePressed("res/close.png",0)
b_1:loadTextureDisabled("res/close.png",0)
b_1:setTitleFontSize(14)
b_1:setTitleColor({r = 65, g = 65, b = 70})
b_1:setLayoutComponentEnabled(true)
b_1:setName("b_1")
b_1:setTag(26)
b_1:setCascadeColorEnabled(true)
b_1:setCascadeOpacityEnabled(true)
b_1:setPosition(569.8348, 950.2913)
layout = ccui.LayoutComponent:bindLayoutComponent(b_1)
layout:setPositionPercentX(0.7914)
layout:setPositionPercentY(0.7424)
layout:setPercentWidth(0.1569)
layout:setPercentHeight(0.0930)
layout:setSize({width = 113.0000, height = 119.0000})
layout:setLeftMargin(513.3348)
layout:setRightMargin(93.6652)
layout:setTopMargin(270.2087)
layout:setBottomMargin(890.7913)
Layer:addChild(b_1)

--Create warning_2
local warning_2 = cc.Sprite:create("res/waitDialog/warning.png")
warning_2:setName("warning_2")
warning_2:setTag(27)
warning_2:setCascadeColorEnabled(true)
warning_2:setCascadeOpacityEnabled(true)
warning_2:setPosition(202.8391, 887.2609)
warning_2:setScaleX(0.8000)
warning_2:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(warning_2)
layout:setPositionPercentX(0.2817)
layout:setPositionPercentY(0.6932)
layout:setSize({width = 116.0000, height = 116.0000})
layout:setLeftMargin(144.8391)
layout:setRightMargin(459.1609)
layout:setTopMargin(334.7391)
layout:setBottomMargin(829.2609)
warning_2:setBlendFunc({src = 770, dst = 771})
Layer:addChild(warning_2)

--Create bm_1
local bm_1 = ccui.TextBMFont:create()
bm_1:setFntFile("fnts/fnt.fnt")
bm_1:setString([[抱歉]])
bm_1:setLayoutComponentEnabled(true)
bm_1:setName("bm_1")
bm_1:setTag(29)
bm_1:setCascadeColorEnabled(true)
bm_1:setCascadeOpacityEnabled(true)
bm_1:setAnchorPoint(0.0000, 0.5000)
bm_1:setPosition(261.4753, 884.9525)
bm_1:setScaleX(1.5000)
bm_1:setScaleY(1.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(bm_1)
layout:setPositionPercentX(0.3632)
layout:setPositionPercentY(0.6914)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0250)
layout:setSize({width = 66.0000, height = 32.0000})
layout:setLeftMargin(261.4753)
layout:setRightMargin(392.5247)
layout:setTopMargin(379.0475)
layout:setBottomMargin(868.9525)
Layer:addChild(bm_1)

--Create bm_2
local bm_2 = ccui.TextBMFont:create()
bm_2:setFntFile("fnts/fnt.fnt")
bm_2:setString([[距离下一次观看视频还需要等待:]])
bm_2:setLayoutComponentEnabled(true)
bm_2:setName("bm_2")
bm_2:setTag(30)
bm_2:setCascadeColorEnabled(true)
bm_2:setCascadeOpacityEnabled(true)
bm_2:setPosition(380.2426, 825.3389)
bm_2:setScaleX(0.7500)
bm_2:setScaleY(0.7500)
bm_2:setColor({r = 30, g = 39, b = 70})
layout = ccui.LayoutComponent:bindLayoutComponent(bm_2)
layout:setPositionPercentX(0.5281)
layout:setPositionPercentY(0.6448)
layout:setPercentWidth(0.2528)
layout:setPercentHeight(0.0250)
layout:setSize({width = 479.0000, height = 32.0000})
layout:setLeftMargin(140.7426)
layout:setRightMargin(100.2573)
layout:setTopMargin(438.6611)
layout:setBottomMargin(809.3389)
Layer:addChild(bm_2)

--Create b_2
local b_2 = ccui.Button:create()
b_2:ignoreContentAdaptWithSize(false)
b_2:loadTextureNormal("res/waitDialog/btn_ok.png",0)
b_2:loadTexturePressed("res/waitDialog/btn_ok.png",0)
b_2:loadTextureDisabled("res/waitDialog/btn_ok.png",0)
b_2:setTitleFontSize(14)
b_2:setTitleColor({r = 65, g = 65, b = 70})
b_2:setLayoutComponentEnabled(true)
b_2:setName("b_2")
b_2:setTag(31)
b_2:setCascadeColorEnabled(true)
b_2:setCascadeOpacityEnabled(true)
b_2:setPosition(360.0000, 624.0705)
layout = ccui.LayoutComponent:bindLayoutComponent(b_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4876)
layout:setPercentWidth(0.2389)
layout:setPercentHeight(0.0547)
layout:setSize({width = 172.0000, height = 70.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(274.0000)
layout:setRightMargin(274.0000)
layout:setTopMargin(620.9295)
layout:setBottomMargin(589.0705)
Layer:addChild(b_2)

--Create bm_3
local bm_3 = ccui.TextBMFont:create()
bm_3:setFntFile("fnts/fnt.fnt")
bm_3:setString([[30:30:30]])
bm_3:setLayoutComponentEnabled(true)
bm_3:setName("bm_3")
bm_3:setTag(32)
bm_3:setCascadeColorEnabled(true)
bm_3:setCascadeOpacityEnabled(true)
bm_3:setAnchorPoint(0.0000, 0.5000)
bm_3:setPosition(224.0000, 736.3840)
bm_3:setScaleX(2.0000)
bm_3:setScaleY(2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bm_3)
layout:setPositionPercentX(0.3111)
layout:setPositionPercentY(0.5753)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0250)
layout:setSize({width = 136.0000, height = 32.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(224.0000)
layout:setRightMargin(360.0000)
layout:setTopMargin(527.6160)
layout:setBottomMargin(720.3840)
Layer:addChild(bm_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

